import type {
  Concert,
  GalleryImage,
  HeroSlide,
  Notice,
  SiteSettings,
  SupportSettings,
} from '../types/content'

export const heroSlides = [
  {
    id: 'hero-slide-1',
    title: '마음을 다한 음악으로 다음 세대를 세웁니다',
    subtitle: '마음을 담은 음악과 함께 빚는 울림',
    description:
      '청소년의 목소리가 음악 안에서 자라도록 무대와 교육의 시간을 이어갑니다.',
    image_url: '/images/hero/hero-01.svg',
    image_alt: '서울모테트청소년합창단 공연 장면',
    primary_cta_label: '입단 안내',
    primary_cta_href: '/join',
    secondary_cta_label: '공연 일정',
    secondary_cta_href: '/concerts',
    display_order: 1,
    is_visible: true,
  },
  {
    id: 'hero-slide-2',
    title: '함께 배우고 함께 노래하는 시간',
    subtitle: '음악 안에서 자라는 마음과 울림',
    description:
      '정기 연습과 무대 경험을 통해 청소년들이 음악의 가치와 공동체의 마음을 배웁니다.',
    image_url: '/images/hero/hero-02.svg',
    image_alt: '서울모테트청소년합창단 연습 장면',
    primary_cta_label: '합창단 소개',
    primary_cta_href: '/about',
    secondary_cta_label: '입단 안내',
    secondary_cta_href: '/join',
    display_order: 2,
    is_visible: true,
  },
  {
    id: 'hero-slide-3',
    title: '무대 위에 이어지는 나눔',
    subtitle: '정기연주회와 초청연주, 봉사연주',
    description:
      '다양한 연주 활동을 통해 합창의 아름다움과 선한 메시지를 전합니다.',
    image_url: '/images/hero/hero-03.svg',
    image_alt: '서울모테트청소년합창단 무대 장면',
    primary_cta_label: '공연 일정',
    primary_cta_href: '/concerts',
    secondary_cta_label: '후원·문의',
    secondary_cta_href: '/contact',
    display_order: 3,
    is_visible: true,
  },
] satisfies HeroSlide[]

export const mockConcerts = [
  {
    id: 'concert-1',
    title: '서울모테트청소년합창단 정기연주회',
    category: 'regular',
    date: '2026-11-28',
    time: '19:30',
    location: '',
    poster_url: '/images/placeholders/poster-placeholder.svg',
    description:
      '서울모테트청소년합창단의 정기연주회 소식을 안내합니다.',
    program: [],
    performers: ['서울모테트청소년합창단'],
    ticket_url: '',
    apply_url: '',
    status: 'scheduled',
    is_visible: true,
    created_at: '2026-06-24T00:00:00.000Z',
    updated_at: '2026-06-24T00:00:00.000Z',
  },
  {
    id: 'concert-2',
    title: '초청연주',
    category: 'invited',
    date: '2026-08-15',
    time: '17:00',
    location: '',
    poster_url: '/images/placeholders/poster-placeholder.svg',
    description: '서울모테트청소년합창단의 초청연주 소식을 안내합니다.',
    program: [],
    performers: ['서울모테트청소년합창단'],
    ticket_url: '',
    apply_url: '',
    status: 'scheduled',
    is_visible: true,
    created_at: '2026-06-24T00:00:00.000Z',
    updated_at: '2026-06-24T00:00:00.000Z',
  },
  {
    id: 'concert-3',
    title: '봉사연주',
    category: 'special',
    date: '2026-12-20',
    time: '15:00',
    location: '',
    poster_url: '/images/placeholders/poster-placeholder.svg',
    description: '음악을 통한 나눔을 실천하는 봉사연주입니다.',
    program: [],
    performers: ['서울모테트청소년합창단'],
    ticket_url: '',
    apply_url: '',
    status: 'scheduled',
    is_visible: true,
    created_at: '2026-06-24T00:00:00.000Z',
    updated_at: '2026-06-24T00:00:00.000Z',
  },
] satisfies Concert[]

export const mockNotices = [
  {
    id: 'notice-1',
    title: '2026 입단 안내',
    category: 'join',
    content: '서울모테트청소년합창단 입단 안내를 확인해 주세요.',
    cover_image_url: '',
    is_important: true,
    is_visible: true,
    created_at: '2026-06-24T00:00:00.000Z',
    updated_at: '2026-06-24T00:00:00.000Z',
  },
  {
    id: 'notice-2',
    title: '공연 일정 안내',
    category: 'concert',
    content: '공연 일정이 확정되는 대로 공지합니다.',
    cover_image_url: '',
    is_important: false,
    is_visible: true,
    created_at: '2026-06-24T00:00:00.000Z',
    updated_at: '2026-06-24T00:00:00.000Z',
  },
  {
    id: 'notice-3',
    title: '갤러리 자료 정리 안내',
    category: 'news',
    content: '기존 사진과 영상 자료를 홈페이지 구조에 맞게 정리합니다.',
    cover_image_url: '',
    is_important: false,
    is_visible: true,
    created_at: '2026-06-24T00:00:00.000Z',
    updated_at: '2026-06-24T00:00:00.000Z',
  },
] satisfies Notice[]

export const mockGallery = Array.from({ length: 6 }, (_, index) => ({
  id: `gallery-${index + 1}`,
  title: `갤러리 이미지 ${index + 1}`,
  category: 'archive',
  description: '',
  image_url: '/images/placeholders/gallery-placeholder.svg',
  image_alt: `서울모테트청소년합창단 갤러리 기본 이미지 ${index + 1}`,
  is_visible: true,
  display_order: index + 1,
  created_at: '2026-06-24T00:00:00.000Z',
  updated_at: '2026-06-24T00:00:00.000Z',
})) satisfies GalleryImage[]

export const mockSiteSettings = {
  id: 'site-settings-default',
  site_title: '서울모테트청소년합창단',
  hero_title: '마음을 다한 음악으로 다음 세대를 세웁니다',
  hero_subtitle: '마음을 담은 음악과 함께 빚는 울림',
  home_hero_eyebrow: 'SEOUL MOTET YOUTH CHOIR',
  home_hero_description:
    '청소년의 목소리가 음악 안에서 자라도록 무대와 교육의 시간을 이어갑니다.',
  home_info_card_1_title: '입단 안내',
  home_info_card_1_description: '모집 대상과 입단 절차를 확인합니다.',
  home_info_card_2_title: '공연 일정',
  home_info_card_2_description: '다가오는 공연과 공지사항을 확인합니다.',
  home_info_card_3_title: '후원·문의',
  home_info_card_3_description: '후원 상담과 문의를 공식 채널로 연결합니다.',
  home_about_title: '청소년의 목소리로 전하는 깊은 울림',
  home_about_button_label: '합창단 소개 보기',
  home_concerts_title: '다가오는 공연',
  home_concerts_description: '서울모테트청소년합창단의 무대를 만나보세요.',
  home_concerts_button_label: '공연 일정 보기',
  home_notices_title: '공지와 소식',
  home_notices_description:
    '입단, 공연, 갤러리 업데이트 등 중요한 소식을 안내합니다.',
  home_notices_button_label: '공지사항 보기',
  home_gallery_title: '활동 갤러리',
  home_gallery_description: '무대와 연습, 기록의 장면을 모았습니다.',
  home_gallery_button_label: '갤러리 보기',
  home_join_title: '서울모테트청소년합창단과 함께 노래할 단원을 기다립니다',
  home_join_button_label: '입단 안내 보기',
  home_support_title: '후원과 문의',
  home_support_button_label: '문의',
  about_summary:
    '서울모테트청소년합창단은 청소년들이 마음을 담은 음악과 함께 부르는 공동체 안에서 음악과 마음, 공동체의 울림을 함께 배워가도록 돕습니다.',
  support_text:
    '서울모테트청소년합창단의 공연, 초청연주, 후원 상담은 공식 문의 페이지에서 이어집니다.',
  join_cta_text:
    '음악을 사랑하는 청소년들이 함께 배우고 성장할 수 있도록 입단 안내와 문의 흐름을 준비했습니다.',
  email: '',
  phone: '02-579-7295',
  fax: '02-579-7293',
  address: '서울특별시 서초구 사임당로 8길 17 서주빌딩 B1',
  instagram_url: '',
  youtube_url: '',
  updated_at: '2026-06-24T00:00:00.000Z',
} satisfies SiteSettings

export const mockSupportSettings = {
  id: 'support-settings-default',
  title: '한 사람의 목소리가 자라기 위해서는\n보이지 않는 많은 손길이 필요합니다',
  subtitle:
    '후원은 다음 세대가 음악 안에서 성장하도록 돕는 약정 접수입니다.',
  description:
    '후원은 단순한 재정 지원이 아니라, 청소년이 음악 안에서 자신을 발견하고 함께 살아가는 법을 배우도록 돕는 동행입니다.',
  message:
    '현재 후원 기능은 온라인 결제가 아니라 후원 약정 접수입니다. 제출된 약정서는 관리자 확인 후 안내 절차에 따라 관리됩니다.',
  individual_amounts: [10000, 20000, 30000, 50000],
  corporate_amounts: [100000, 200000, 300000, 500000, 1000000],
  allow_custom_amount: true,
  bank_name: '',
  bank_account_number: '',
  bank_account_holder: '',
  bank_note: '후원 계좌 정보는 관리자 CMS에서 등록하면 표시됩니다.',
  enable_online_submission: true,
  form_note:
    '입력한 후원 약정 정보는 관리자에게만 전달되며 공개 화면에는 표시되지 않습니다.',
  privacy_notice:
    '작성하신 개인정보는 후원 안내 및 약정 확인 목적으로만 사용되며, 관리자만 조회할 수 있습니다.',
  print_note:
    '작성 후 인쇄하거나 PDF로 저장할 수 있습니다. 온라인 제출 시 동일한 내용이 관리자 CMS에 저장됩니다.',
  print_button_label: '약정서 인쇄하기',
  submit_button_label: '후원 약정 제출',
  success_message: '후원 약정이 접수되었습니다. 확인 후 연락드리겠습니다.',
  contact_phone: '',
  contact_email: '',
  homepage_url: '',
  organization_name: '서울모테트청소년합창단',
  footer_note:
    '입력 내용은 관리자 CMS에 안전하게 저장되며 공개 화면에는 표시되지 않습니다.',
  is_visible: true,
  updated_at: '2026-06-24T00:00:00.000Z',
} satisfies SupportSettings
