import type {
  Concert,
  GalleryImage,
  HeroSlide,
  Notice,
  SiteSettings,
} from '../types/content'

export const heroSlides = [
  {
    id: 'hero-slide-1',
    title: '서울모테트청소년합창단',
    subtitle: '맑은 목소리로 전하는 깊은 울림',
    description:
      '청소년의 순수한 목소리와 클래식 합창의 깊이를 현대적인 무대 경험으로 전합니다.',
    image_url: '/images/hero/hero-01.svg',
    image_alt: '서울모테트청소년합창단 공연 사진',
    primary_cta_label: '공연 일정 보기',
    primary_cta_href: '/concerts',
    secondary_cta_label: '입단 안내 보기',
    secondary_cta_href: '/join',
    display_order: 1,
    is_visible: true,
  },
  {
    id: 'hero-slide-2',
    title: '함께 배우고 함께 노래하는 시간',
    subtitle: '음악 안에서 자라는 지성과 인성',
    description:
      '정기연습과 무대 경험을 통해 청소년들이 음악의 가치와 협업의 힘을 배웁니다.',
    image_url: '/images/hero/hero-02.svg',
    image_alt: '서울모테트청소년합창단 연습 장면',
    primary_cta_label: '합창단 소개',
    primary_cta_href: '/about',
    secondary_cta_label: '입단 안내 보기',
    secondary_cta_href: '/join',
    display_order: 2,
    is_visible: true,
  },
  {
    id: 'hero-slide-3',
    title: '무대 위에서 이어지는 나눔',
    subtitle: '정기연주와 초청연주, 봉사연주',
    description:
      '다양한 연주 활동을 통해 합창의 아름다움과 따뜻한 메시지를 전합니다.',
    image_url: '/images/hero/hero-03.svg',
    image_alt: '서울모테트청소년합창단 무대 장면',
    primary_cta_label: '갤러리 보기',
    primary_cta_href: '/gallery',
    secondary_cta_label: '후원·문의',
    secondary_cta_href: '/contact',
    display_order: 3,
    is_visible: true,
  },
] satisfies HeroSlide[]

export const mockConcerts = [
  {
    id: 'concert-1',
    title: '서울모테트청소년합창단 정기연주회',
    category: '정기연주회',
    date: '2026-11-28',
    time: '19:30',
    location: '공연장 미정',
    poster_url: '/images/placeholders/poster-placeholder.svg',
    description: '정기연주회 정보가 확정되면 관리자 CMS에서 수정합니다.',
    program: ['TODO: 프로그램 확정 후 입력'],
    performers: ['서울모테트청소년합창단'],
    ticket_url: '',
    apply_url: '',
    status: 'scheduled',
    is_visible: true,
    created_at: '2026-06-24T00:00:00.000Z',
    updated_at: '2026-06-24T00:00:00.000Z',
  },
  {
    id: 'concert-2',
    title: '초청연주',
    category: '초청연주',
    date: '2026-08-15',
    time: '17:00',
    location: '초청 기관 확정 후 입력',
    poster_url: '/images/placeholders/poster-placeholder.svg',
    description: '초청연주 세부 정보는 추후 공개됩니다.',
    program: [],
    performers: ['서울모테트청소년합창단'],
    ticket_url: '',
    apply_url: '',
    status: 'scheduled',
    is_visible: true,
    created_at: '2026-06-24T00:00:00.000Z',
    updated_at: '2026-06-24T00:00:00.000Z',
  },
  {
    id: 'concert-3',
    title: '봉사연주',
    category: '봉사연주',
    date: '2026-12-20',
    time: '15:00',
    location: '장소 확정 후 입력',
    poster_url: '/images/placeholders/poster-placeholder.svg',
    description: '음악을 통한 나눔을 실천하는 봉사연주입니다.',
    program: [],
    performers: ['서울모테트청소년합창단'],
    ticket_url: '',
    apply_url: '',
    status: 'scheduled',
    is_visible: true,
    created_at: '2026-06-24T00:00:00.000Z',
    updated_at: '2026-06-24T00:00:00.000Z',
  },
] satisfies Concert[]

export const mockNotices = [
  {
    id: 'notice-1',
    title: '2026년 입단 안내 준비 중',
    category: 'notice',
    content: '입단 안내 상세 내용은 추후 관리자 CMS에서 등록합니다.',
    cover_image_url: '',
    is_important: true,
    is_visible: true,
    created_at: '2026-06-24T00:00:00.000Z',
    updated_at: '2026-06-24T00:00:00.000Z',
  },
  {
    id: 'notice-2',
    title: '공연 일정 업데이트 예정',
    category: 'notice',
    content: '공연 일정이 확정되는 대로 공지합니다.',
    cover_image_url: '',
    is_important: false,
    is_visible: true,
    created_at: '2026-06-24T00:00:00.000Z',
    updated_at: '2026-06-24T00:00:00.000Z',
  },
  {
    id: 'notice-3',
    title: '갤러리 자료 정리 안내',
    category: 'news',
    content: '기존 사진과 영상 자료를 새 홈페이지 구조에 맞춰 정리합니다.',
    cover_image_url: '',
    is_important: false,
    is_visible: true,
    created_at: '2026-06-24T00:00:00.000Z',
    updated_at: '2026-06-24T00:00:00.000Z',
  },
] satisfies Notice[]

export const mockGallery = Array.from({ length: 6 }, (_, index) => ({
  id: `gallery-${index + 1}`,
  title: `갤러리 이미지 ${index + 1}`,
  category: 'archive',
  image_url: '/images/placeholders/gallery-placeholder.svg',
  image_alt: `서울모테트청소년합창단 갤러리 placeholder ${index + 1}`,
  is_visible: true,
  display_order: index + 1,
  created_at: '2026-06-24T00:00:00.000Z',
  updated_at: '2026-06-24T00:00:00.000Z',
})) satisfies GalleryImage[]

export const mockSiteSettings = {
  id: 'site-settings-default',
  site_title: '서울모테트청소년합창단',
  hero_title: '서울모테트청소년합창단',
  hero_subtitle: '맑은 목소리로 전하는 깊은 울림',
  about_summary:
    '서울모테트음악재단 청소년아카데미 부설 합창단으로, 청소년들이 음악 안에서 지성과 인성을 함께 기르도록 돕습니다.',
  email: '',
  phone: '02-579-7295',
  fax: '02-579-7293',
  address: '서울특별시 서초구 사임당로 8길 17 서주빌딩 B1',
  instagram_url: '',
  youtube_url: '',
  updated_at: '2026-06-24T00:00:00.000Z',
} satisfies SiteSettings
