export type SiteTextInputType = 'label' | 'text' | 'textarea' | 'url'

export type SiteTextDefinition = {
  defaultValue: string
  description: string
  groupName: string
  inputType: SiteTextInputType
  key: string
  label: string
  sortOrder: number
}

export const siteTextDefinitions = [
  {
    defaultValue: 'SEOUL',
    description: '홈 히어로의 첫 번째 큰 영문 문구입니다.',
    groupName: 'home.hero',
    inputType: 'text',
    key: 'home.hero.title.line1',
    label: '히어로 제목 1행',
    sortOrder: 10,
  },
  {
    defaultValue: 'MOTET',
    description: '홈 히어로의 두 번째 큰 영문 문구입니다.',
    groupName: 'home.hero',
    inputType: 'text',
    key: 'home.hero.title.line2',
    label: '히어로 제목 2행',
    sortOrder: 20,
  },
  {
    defaultValue: 'YOUTH',
    description: '홈 히어로의 세 번째 큰 영문 문구입니다.',
    groupName: 'home.hero',
    inputType: 'text',
    key: 'home.hero.title.line3',
    label: '히어로 제목 3행',
    sortOrder: 21,
  },
  {
    defaultValue: 'CHOIR',
    description: '홈 히어로의 네 번째 큰 영문 문구입니다.',
    groupName: 'home.hero',
    inputType: 'text',
    key: 'home.hero.title.line4',
    label: '히어로 제목 4행',
    sortOrder: 22,
  },
  {
    defaultValue:
      '서울모테트청소년합창단은 청소년이 합창을 배우고 정기 연습과 공연을 경험하는 음악교육 공동체입니다.',
    description: '히어로 제목 아래에 표시되는 보조 문구입니다.',
    groupName: 'home.hero',
    inputType: 'textarea',
    key: 'home.hero.subtitle',
    label: '히어로 설명',
    sortOrder: 30,
  },
  {
    defaultValue: '서울모테트청소년합창단',
    description: '히어로 상단의 한글 라벨입니다.',
    groupName: 'home.hero',
    inputType: 'text',
    key: 'home.hero.eyebrow',
    label: '히어로 키커',
    sortOrder: 40,
  },
  {
    defaultValue: '합창 교육',
    description: '히어로 하단 가치 칩 1입니다.',
    groupName: 'home.hero',
    inputType: 'text',
    key: 'home.hero.chip1',
    label: '히어로 가치 칩 1',
    sortOrder: 50,
  },
  {
    defaultValue: '정기 연습',
    description: '히어로 하단 가치 칩 2입니다.',
    groupName: 'home.hero',
    inputType: 'text',
    key: 'home.hero.chip2',
    label: '히어로 가치 칩 2',
    sortOrder: 60,
  },
  {
    defaultValue: '공연 활동',
    description: '히어로 하단 가치 칩 3입니다.',
    groupName: 'home.hero',
    inputType: 'text',
    key: 'home.hero.chip3',
    label: '히어로 가치 칩 3',
    sortOrder: 70,
  },
  {
    defaultValue: '입단 안내',
    description: '히어로의 첫 번째 CTA 버튼 문구입니다.',
    groupName: 'home.hero',
    inputType: 'text',
    key: 'home.hero.cta.primary',
    label: '히어로 기본 CTA',
    sortOrder: 80,
  },
  {
    defaultValue: '공연 일정',
    description: '히어로의 두 번째 CTA 버튼 문구입니다.',
    groupName: 'home.hero',
    inputType: 'text',
    key: 'home.hero.cta.secondary',
    label: '히어로 보조 CTA',
    sortOrder: 90,
  },
  {
    defaultValue: '입단 안내',
    description: '빠른 진입 카드의 입단 제목입니다.',
    groupName: 'home.quick',
    inputType: 'text',
    key: 'home.quick.join.title',
    label: '입단 카드 제목',
    sortOrder: 110,
  },
  {
    defaultValue:
      '모집 대상, 연습 시간, 지원 절차를 확인하고 입단지원서로 이동합니다.',
    description: '빠른 진입 카드의 입단 설명입니다.',
    groupName: 'home.quick',
    inputType: 'textarea',
    key: 'home.quick.join.description',
    label: '입단 카드 설명',
    sortOrder: 120,
  },
  {
    defaultValue: '공연 일정',
    description: '빠른 진입 카드의 공연 제목입니다.',
    groupName: 'home.quick',
    inputType: 'text',
    key: 'home.quick.concert.title',
    label: '공연 카드 제목',
    sortOrder: 130,
  },
  {
    defaultValue:
      '정기연주회, 초청연주, 공지사항을 확인합니다.',
    description: '빠른 진입 카드의 공연 설명입니다.',
    groupName: 'home.quick',
    inputType: 'textarea',
    key: 'home.quick.concert.description',
    label: '공연 카드 설명',
    sortOrder: 140,
  },
  {
    defaultValue: '후원·문의',
    description: '빠른 진입 카드의 후원/문의 제목입니다.',
    groupName: 'home.quick',
    inputType: 'text',
    key: 'home.quick.support.title',
    label: '후원·문의 카드 제목',
    sortOrder: 150,
  },
  {
    defaultValue:
      '후원 상담과 일반 문의를 공식 문의 폼으로 접수합니다.',
    description: '빠른 진입 카드의 후원/문의 설명입니다.',
    groupName: 'home.quick',
    inputType: 'textarea',
    key: 'home.quick.support.description',
    label: '후원·문의 카드 설명',
    sortOrder: 160,
  },
  {
    defaultValue: '갤러리',
    description: '필요 시 빠른 진입 카드에 사용할 갤러리 제목입니다.',
    groupName: 'home.quick',
    inputType: 'text',
    key: 'home.quick.gallery.title',
    label: '갤러리 카드 제목',
    sortOrder: 170,
  },
  {
    defaultValue: '활동 사진과 영상 기록을 확인합니다.',
    description: '필요 시 빠른 진입 카드에 사용할 갤러리 설명입니다.',
    groupName: 'home.quick',
    inputType: 'textarea',
    key: 'home.quick.gallery.description',
    label: '갤러리 카드 설명',
    sortOrder: 180,
  },
  {
    defaultValue: 'ABOUT',
    description: '홈 소개 섹션의 상단 라벨입니다.',
    groupName: 'home.about',
    inputType: 'text',
    key: 'home.about.kicker',
    label: '소개 키커',
    sortOrder: 210,
  },
  {
    defaultValue: '서울모테트청소년합창단 소개',
    description: '홈 소개 섹션 제목입니다.',
    groupName: 'home.about',
    inputType: 'text',
    key: 'home.about.title',
    label: '소개 제목',
    sortOrder: 220,
  },
  {
    defaultValue:
      '서울모테트청소년합창단은 청소년이 합창의 기본기, 악보 읽기, 무대 경험을 체계적으로 배우는 합창교육 공동체입니다.\n\n정기 연습과 공연 활동을 통해 발성, 앙상블, 협업 태도를 함께 익힙니다.',
    description: '홈 앞쪽에 짧게 노출되는 합창단 소개 문구입니다.',
    groupName: 'home.about',
    inputType: 'textarea',
    key: 'home.about.body',
    label: '소개 본문',
    sortOrder: 230,
  },
  {
    defaultValue: '합창단 소개 보기',
    description: '소개 섹션 CTA 버튼 문구입니다.',
    groupName: 'home.about',
    inputType: 'text',
    key: 'home.about.cta',
    label: '소개 CTA',
    sortOrder: 240,
  },
  {
    defaultValue: 'JOIN',
    description: '입단 CTA 섹션의 상단 라벨입니다.',
    groupName: 'home.join',
    inputType: 'text',
    key: 'home.join.kicker',
    label: '입단 키커',
    sortOrder: 310,
  },
  {
    defaultValue: '입단 안내',
    description: '홈 조기 입단 CTA 제목입니다.',
    groupName: 'home.join',
    inputType: 'text',
    key: 'home.join.title',
    label: '입단 CTA 제목',
    sortOrder: 320,
  },
  {
    defaultValue:
      '모집 대상, 연습 일정, 오디션 절차를 확인한 뒤 입단지원서를 제출할 수 있습니다. 제출 후 담당자가 보호자 연락처로 안내합니다.',
    description: '홈 조기 입단 CTA 본문입니다.',
    groupName: 'home.join',
    inputType: 'textarea',
    key: 'home.join.body',
    label: '입단 CTA 본문',
    sortOrder: 330,
  },
  {
    defaultValue: '합창 활동에 관심이 있고 정기 연습에 참여할 수 있는 청소년',
    description: '입단 CTA의 모집 대상 요약입니다.',
    groupName: 'home.join',
    inputType: 'textarea',
    key: 'home.join.target',
    label: '모집 대상',
    sortOrder: 340,
  },
  {
    defaultValue: '정기 연습, 특별 연습, 공연 준비 일정은 입단 안내에서 확인',
    description: '입단 CTA의 연습 안내 요약입니다.',
    groupName: 'home.join',
    inputType: 'textarea',
    key: 'home.join.schedule',
    label: '연습 안내',
    sortOrder: 350,
  },
  {
    defaultValue: '지원서 작성 → 보호자 연락처로 안내 → 간단한 음역 확인과 입단 상담',
    description: '입단 CTA의 절차 요약입니다.',
    groupName: 'home.join',
    inputType: 'textarea',
    key: 'home.join.process',
    label: '입단 절차',
    sortOrder: 360,
  },
  {
    defaultValue: '입단지원서 작성하기',
    description: '입단 CTA 버튼 문구입니다.',
    groupName: 'home.join',
    inputType: 'text',
    key: 'home.join.cta',
    label: '입단 CTA 버튼',
    sortOrder: 370,
  },
  {
    defaultValue: 'CONCERTS & NEWS',
    description: '공연·공지 섹션 상단 라벨입니다.',
    groupName: 'home.concert',
    inputType: 'text',
    key: 'home.concert.kicker',
    label: '공연 키커',
    sortOrder: 410,
  },
  {
    defaultValue: '공연과 소식',
    description: '공연·공지 섹션 제목입니다.',
    groupName: 'home.concert',
    inputType: 'text',
    key: 'home.concert.title',
    label: '공연 섹션 제목',
    sortOrder: 420,
  },
  {
    defaultValue:
      '다가오는 공연의 날짜, 장소, 공지사항을 확인합니다. 공연 정보가 확정되면 이 섹션에 반영됩니다.',
    description: '공연·공지 섹션 보조 설명입니다.',
    groupName: 'home.concert',
    inputType: 'textarea',
    key: 'home.concert.description',
    label: '공연 섹션 설명',
    sortOrder: 430,
  },
  {
    defaultValue: '공연 일정 보기',
    description: '공연 목록 CTA 문구입니다.',
    groupName: 'home.concert',
    inputType: 'text',
    key: 'home.concert.cta.schedule',
    label: '공연 일정 CTA',
    sortOrder: 440,
  },
  {
    defaultValue: '공지사항 보기',
    description: '공지 목록 CTA 문구입니다.',
    groupName: 'home.concert',
    inputType: 'text',
    key: 'home.concert.cta.notice',
    label: '공지 CTA',
    sortOrder: 450,
  },
  {
    defaultValue: '자세히 보기',
    description: '공연 카드 상세 버튼 문구입니다.',
    groupName: 'home.concert',
    inputType: 'text',
    key: 'home.concert.cta.more',
    label: '공연 상세 CTA',
    sortOrder: 460,
  },
  {
    defaultValue: '문의',
    description: '공연 카드 문의 버튼 문구입니다.',
    groupName: 'home.concert',
    inputType: 'text',
    key: 'home.concert.cta.inquiry',
    label: '공연 문의 CTA',
    sortOrder: 470,
  },
  {
    defaultValue: '합창단 활동을\n한눈에 보는\nMotet Score',
    description: 'Motet Score 표지 제목입니다.',
    groupName: 'home.score',
    inputType: 'textarea',
    key: 'home.score.cover.title',
    label: '악보 표지 제목',
    sortOrder: 510,
  },
  {
    defaultValue:
      '연습, 공연 준비, 주요 안내를 악보집 형식으로 정리했습니다.',
    description: 'Motet Score 표지 설명입니다.',
    groupName: 'home.score',
    inputType: 'textarea',
    key: 'home.score.cover.body',
    label: '악보 표지 설명',
    sortOrder: 520,
  },
  {
    defaultValue: 'MOTET SCORE',
    description: 'Motet Score 내부 왼쪽 라벨입니다.',
    groupName: 'home.score',
    inputType: 'text',
    key: 'home.score.left.kicker',
    label: '악보 왼쪽 키커',
    sortOrder: 530,
  },
  {
    defaultValue: '합창 교육',
    description: 'Motet Score 왼쪽 보조 제목입니다.',
    groupName: 'home.score',
    inputType: 'text',
    key: 'home.score.left.title',
    label: '악보 왼쪽 제목',
    sortOrder: 540,
  },
  {
    defaultValue:
      '입단, 연습, 작품 준비 과정에서 악보 읽기와 앙상블 기본기를 배웁니다.',
    description: 'Motet Score 왼쪽 본문입니다.',
    groupName: 'home.score',
    inputType: 'textarea',
    key: 'home.score.left.body',
    label: '악보 왼쪽 본문',
    sortOrder: 550,
  },
  {
    defaultValue: '공동체 연습',
    description: 'Motet Score 오른쪽 보조 제목입니다.',
    groupName: 'home.score',
    inputType: 'text',
    key: 'home.score.right.title',
    label: '악보 오른쪽 제목',
    sortOrder: 560,
  },
  {
    defaultValue:
      '파트별 역할을 익히고, 다른 단원의 소리를 들으며 함께 맞춰 갑니다.',
    description: 'Motet Score 오른쪽 본문입니다.',
    groupName: 'home.score',
    inputType: 'textarea',
    key: 'home.score.right.body',
    label: '악보 오른쪽 본문',
    sortOrder: 570,
  },
  {
    defaultValue: '연습과 공연을\n함께 확인합니다',
    description: 'Motet Score 최종 페이지 제목입니다.',
    groupName: 'home.score',
    inputType: 'textarea',
    key: 'home.score.final.title',
    label: '악보 최종 제목',
    sortOrder: 580,
  },
  {
    defaultValue:
      '합창단의 교육 방향과 활동 흐름을 한 화면에서 안내합니다.',
    description: 'Motet Score 최종 페이지 본문입니다.',
    groupName: 'home.score',
    inputType: 'textarea',
    key: 'home.score.final.body',
    label: '악보 최종 본문',
    sortOrder: 590,
  },
  {
    defaultValue: '발성, 악보, 파트, 앙상블, 공연, 안내',
    description: '데스크톱 악보 전환 중 표시되는 가치 단어 목록입니다.',
    groupName: 'home.score',
    inputType: 'textarea',
    key: 'home.score.value.list',
    label: '악보 가치 단어',
    sortOrder: 600,
  },
  {
    defaultValue: 'ARCHIVE',
    description: '갤러리 섹션 상단 라벨입니다.',
    groupName: 'home.gallery',
    inputType: 'text',
    key: 'home.gallery.kicker',
    label: '갤러리 키커',
    sortOrder: 610,
  },
  {
    defaultValue: '활동 기록',
    description: '갤러리 섹션 제목입니다.',
    groupName: 'home.gallery',
    inputType: 'text',
    key: 'home.gallery.title',
    label: '갤러리 제목',
    sortOrder: 620,
  },
  {
    defaultValue:
      '공연 사진, 연습 사진, 영상, 포스터를 모아 확인합니다.',
    description: '갤러리 섹션 설명입니다.',
    groupName: 'home.gallery',
    inputType: 'textarea',
    key: 'home.gallery.description',
    label: '갤러리 설명',
    sortOrder: 630,
  },
  {
    defaultValue: '갤러리 보기',
    description: '갤러리 CTA 버튼 문구입니다.',
    groupName: 'home.gallery',
    inputType: 'text',
    key: 'home.gallery.cta',
    label: '갤러리 CTA',
    sortOrder: 640,
  },
  {
    defaultValue: '등록된 갤러리 자료가 없습니다',
    description: '홈 갤러리 미리보기의 빈 상태 제목입니다.',
    groupName: 'home.gallery',
    inputType: 'text',
    key: 'home.gallery.empty.title',
    label: '갤러리 빈 상태 제목',
    sortOrder: 650,
  },
  {
    defaultValue: '사진과 영상이 등록되면 이 공간에 표시됩니다.',
    description: '홈 갤러리 미리보기의 빈 상태 설명입니다.',
    groupName: 'home.gallery',
    inputType: 'textarea',
    key: 'home.gallery.empty.description',
    label: '갤러리 빈 상태 설명',
    sortOrder: 660,
  },
  {
    defaultValue: '후원·문의',
    description: '후원·문의 섹션 제목입니다.',
    groupName: 'home.support',
    inputType: 'text',
    key: 'home.support.title',
    label: '후원 섹션 제목',
    sortOrder: 710,
  },
  {
    defaultValue:
      '후원금은 악보와 교육 자료, 연습과 공연 준비, 국제교류 활동에 사용됩니다. 후원 상담과 일반 문의는 공식 문의 폼으로 접수합니다.',
    description: '후원·문의 섹션 본문입니다.',
    groupName: 'home.support',
    inputType: 'textarea',
    key: 'home.support.description',
    label: '후원 섹션 본문',
    sortOrder: 720,
  },
  {
    defaultValue: '후원 상담 신청',
    description: '후원 상담 CTA 문구입니다.',
    groupName: 'home.support',
    inputType: 'text',
    key: 'home.support.cta.primary',
    label: '후원 상담 CTA',
    sortOrder: 730,
  },
  {
    defaultValue: '문의',
    description: '후원 섹션 일반 문의 CTA 문구입니다.',
    groupName: 'home.support',
    inputType: 'text',
    key: 'home.support.cta.secondary',
    label: '후원 문의 CTA',
    sortOrder: 740,
  },
  {
    defaultValue: '문의 접수 안내',
    description: '후원 카드 제목입니다.',
    groupName: 'home.support',
    inputType: 'text',
    key: 'home.support.card.title',
    label: '후원 카드 제목',
    sortOrder: 750,
  },
  {
    defaultValue:
      '공연 초청, 후원 상담, 입단 문의를 공식 문의 폼으로 접수합니다. 담당자가 확인한 뒤 이메일 또는 연락처로 안내합니다.',
    description: '후원 카드 설명입니다.',
    groupName: 'home.support',
    inputType: 'textarea',
    key: 'home.support.card.description',
    label: '후원 카드 설명',
    sortOrder: 760,
  },
  {
    defaultValue: '문의',
    description: '홈 하단 짧은 후원·문의 연결 CTA입니다.',
    groupName: 'home.support',
    inputType: 'text',
    key: 'home.support.short.cta',
    label: '짧은 후원 문의 CTA',
    sortOrder: 770,
  },
  {
    defaultValue: '합창 교육과 공연 활동',
    description: '푸터 태그라인 첫 번째 줄입니다.',
    groupName: 'home.footer',
    inputType: 'text',
    key: 'footer.tagline.line1',
    label: '푸터 태그라인 1행',
    sortOrder: 810,
  },
  {
    defaultValue: '다음 세대를 세웁니다',
    description: '푸터 태그라인 두 번째 줄입니다.',
    groupName: 'home.footer',
    inputType: 'text',
    key: 'footer.tagline.line2',
    label: '푸터 태그라인 2행',
    sortOrder: 820,
  },
  {
    defaultValue: '입단 안내',
    description: '푸터 빠른 메뉴 입단 문구입니다.',
    groupName: 'home.footer',
    inputType: 'text',
    key: 'footer.quick.join',
    label: '푸터 입단 메뉴',
    sortOrder: 830,
  },
  {
    defaultValue: '공연 일정',
    description: '푸터 빠른 메뉴 공연 문구입니다.',
    groupName: 'home.footer',
    inputType: 'text',
    key: 'footer.quick.concert',
    label: '푸터 공연 메뉴',
    sortOrder: 840,
  },
  {
    defaultValue: '후원·문의',
    description: '푸터 빠른 메뉴 후원 문구입니다.',
    groupName: 'home.footer',
    inputType: 'text',
    key: 'footer.quick.support',
    label: '푸터 후원 메뉴',
    sortOrder: 850,
  },
  {
    defaultValue: '갤러리',
    description: '푸터 빠른 메뉴 갤러리 문구입니다.',
    groupName: 'home.footer',
    inputType: 'text',
    key: 'footer.quick.gallery',
    label: '푸터 갤러리 메뉴',
    sortOrder: 860,
  },
  {
    defaultValue: '합창단 소개',
    description: '푸터 빠른 메뉴 소개 문구입니다.',
    groupName: 'home.footer',
    inputType: 'text',
    key: 'footer.quick.about',
    label: '푸터 소개 메뉴',
    sortOrder: 870,
  },
  {
    defaultValue: '개인정보 처리 안내',
    description: '푸터 개인정보 안내 문구입니다.',
    groupName: 'home.footer',
    inputType: 'text',
    key: 'footer.privacy',
    label: '푸터 개인정보 문구',
    sortOrder: 880,
  },
  {
    defaultValue: '문의',
    description: '공통 문의 CTA 문구입니다.',
    groupName: 'common.button',
    inputType: 'text',
    key: 'common.cta.inquiry',
    label: '공통 문의 CTA',
    sortOrder: 910,
  },
  {
    defaultValue: '자세히 보기',
    description: '공통 상세 CTA 문구입니다.',
    groupName: 'common.button',
    inputType: 'text',
    key: 'common.cta.more',
    label: '공통 상세 CTA',
    sortOrder: 920,
  },
  {
    defaultValue: '입단 안내',
    description: '공통 입단 CTA 문구입니다.',
    groupName: 'common.button',
    inputType: 'text',
    key: 'common.cta.join',
    label: '공통 입단 CTA',
    sortOrder: 930,
  },
  {
    defaultValue: '공연 일정',
    description: '공통 공연 CTA 문구입니다.',
    groupName: 'common.button',
    inputType: 'text',
    key: 'common.cta.concert',
    label: '공통 공연 CTA',
    sortOrder: 940,
  },
  {
    defaultValue: 'SEOUL\nMOTET\nYOUTH\nCHOIR',
    description: '기존 키 호환용 히어로 영문 제목입니다.',
    groupName: 'home.hero',
    inputType: 'textarea',
    key: 'home.hero.title',
    label: '히어로 제목',
    sortOrder: 950,
  },
  {
    defaultValue:
      '서울모테트청소년합창단은 청소년이 합창을 배우고 정기 연습과 공연을 경험하는 음악교육 공동체입니다.',
    description: '기존 키 호환용 히어로 설명입니다.',
    groupName: 'home.hero',
    inputType: 'textarea',
    key: 'home.hero.description',
    label: '히어로 설명',
    sortOrder: 960,
  },
  {
    defaultValue: '입단 안내',
    description: '기존 key 호환용 빠른 카드 1 제목입니다.',
    groupName: 'home.quick',
    inputType: 'text',
    key: 'home.quick.1.title',
    label: '빠른 카드 1 제목',
    sortOrder: 970,
  },
  {
    defaultValue:
      '모집 대상, 연습 시간, 지원 절차를 확인하고 입단지원서로 이동합니다.',
    description: '기존 key 호환용 빠른 카드 1 설명입니다.',
    groupName: 'home.quick',
    inputType: 'textarea',
    key: 'home.quick.1.description',
    label: '빠른 카드 1 설명',
    sortOrder: 980,
  },
  {
    defaultValue: '공연 일정',
    description: '기존 key 호환용 빠른 카드 2 제목입니다.',
    groupName: 'home.quick',
    inputType: 'text',
    key: 'home.quick.2.title',
    label: '빠른 카드 2 제목',
    sortOrder: 990,
  },
  {
    defaultValue:
      '정기연주회, 초청연주, 공지사항을 확인합니다.',
    description: '기존 key 호환용 빠른 카드 2 설명입니다.',
    groupName: 'home.quick',
    inputType: 'textarea',
    key: 'home.quick.2.description',
    label: '빠른 카드 2 설명',
    sortOrder: 1000,
  },
  {
    defaultValue: '후원·문의',
    description: '기존 key 호환용 빠른 카드 3 제목입니다.',
    groupName: 'home.quick',
    inputType: 'text',
    key: 'home.quick.3.title',
    label: '빠른 카드 3 제목',
    sortOrder: 1010,
  },
  {
    defaultValue:
      '후원 상담과 일반 문의를 공식 문의 폼으로 접수합니다.',
    description: '기존 key 호환용 빠른 카드 3 설명입니다.',
    groupName: 'home.quick',
    inputType: 'textarea',
    key: 'home.quick.3.description',
    label: '빠른 카드 3 설명',
    sortOrder: 1020,
  },
  {
    defaultValue: '공연 일정 보기',
    description: '기존 key 호환용 공연 CTA입니다.',
    groupName: 'home.concert',
    inputType: 'text',
    key: 'home.concert.concertButton',
    label: '공연 일정 버튼',
    sortOrder: 1030,
  },
  {
    defaultValue: '공지사항 보기',
    description: '기존 key 호환용 공지 CTA입니다.',
    groupName: 'home.concert',
    inputType: 'text',
    key: 'home.concert.noticeButton',
    label: '공지사항 버튼',
    sortOrder: 1040,
  },
  {
    defaultValue: 'PROGRAM',
    description: '기존 key 호환용 공연 고스트 텍스트입니다.',
    groupName: 'home.concert',
    inputType: 'text',
    key: 'home.concert.ghost',
    label: '공연 배경 텍스트',
    sortOrder: 1050,
  },
  {
    defaultValue: 'PROGRAM NOTE',
    description: '기존 key 호환용 공연 프로그램 라벨입니다.',
    groupName: 'home.concert',
    inputType: 'text',
    key: 'home.concert.programNoteLabel',
    label: '프로그램 노트 라벨',
    sortOrder: 1060,
  },
  {
    defaultValue: '공연과 소식',
    description: '기존 key 호환용 공연 섹션 제목입니다.',
    groupName: 'home.concert',
    inputType: 'text',
    key: 'home.concert.sectionTitle',
    label: '공연 섹션 제목',
    sortOrder: 1070,
  },
  {
    defaultValue: '합창단 활동을\n한눈에 보는\nMotet Score',
    description: '기존 key 호환용 Motet Score 표지 제목입니다.',
    groupName: 'home.score',
    inputType: 'textarea',
    key: 'home.scorebook.coverTitle',
    label: '악보 표지 제목',
    sortOrder: 1080,
  },
  {
    defaultValue:
      '연습, 공연 준비, 주요 안내를 악보집 형식으로 정리했습니다.',
    description: '기존 key 호환용 Motet Score 표지 설명입니다.',
    groupName: 'home.score',
    inputType: 'textarea',
    key: 'home.scorebook.coverDescription',
    label: '악보 표지 설명',
    sortOrder: 1090,
  },
  {
    defaultValue: '연습과 공연을\n함께 확인합니다',
    description: '기존 key 호환용 Motet Score 최종 제목입니다.',
    groupName: 'home.score',
    inputType: 'textarea',
    key: 'home.scorebook.finalTitle',
    label: '악보 최종 제목',
    sortOrder: 1100,
  },
  {
    defaultValue:
      '합창단의 교육 방향과 활동 흐름을 한 화면에서 안내합니다.',
    description: '기존 key 호환용 Motet Score 최종 본문입니다.',
    groupName: 'home.score',
    inputType: 'textarea',
    key: 'home.scorebook.finalDescription',
    label: '악보 최종 본문',
    sortOrder: 1110,
  },
  {
    defaultValue: '공동체 연습',
    description: '기존 key 호환용 Motet Score 오른쪽 제목입니다.',
    groupName: 'home.score',
    inputType: 'text',
    key: 'home.scorebook.rightTitle',
    label: '악보 오른쪽 제목',
    sortOrder: 1120,
  },
  {
    defaultValue: 'ARCHIVE',
    description: '기존 key 호환용 갤러리 키커입니다.',
    groupName: 'home.gallery',
    inputType: 'text',
    key: 'home.gallery.eyebrow',
    label: '갤러리 키커',
    sortOrder: 1130,
  },
  {
    defaultValue: '활동 기록',
    description: '기존 key 호환용 갤러리 제목입니다.',
    groupName: 'home.gallery',
    inputType: 'text',
    key: 'home.gallery.sectionTitle',
    label: '갤러리 제목',
    sortOrder: 1140,
  },
  {
    defaultValue:
      '공연 사진, 연습 사진, 영상, 포스터를 모아 확인합니다.',
    description: '기존 key 호환용 갤러리 설명입니다.',
    groupName: 'home.gallery',
    inputType: 'textarea',
    key: 'home.gallery.sectionDescription',
    label: '갤러리 설명',
    sortOrder: 1150,
  },
  {
    defaultValue: '후원 상담 신청',
    description: '기존 key 호환용 후원 상담 CTA입니다.',
    groupName: 'home.support',
    inputType: 'text',
    key: 'home.support.button',
    label: '후원 상담 CTA',
    sortOrder: 1160,
  },
  {
    defaultValue: '문의',
    description: '기존 key 호환용 후원 문의 CTA입니다.',
    groupName: 'home.support',
    inputType: 'text',
    key: 'home.support.secondaryButton',
    label: '후원 문의 CTA',
    sortOrder: 1170,
  },
  {
    defaultValue: '문의 접수 안내',
    description: '기존 key 호환용 후원 카드 제목입니다.',
    groupName: 'home.support',
    inputType: 'text',
    key: 'home.support.cardTitle',
    label: '후원 카드 제목',
    sortOrder: 1180,
  },
  {
    defaultValue:
      '공연 초청, 후원 상담, 입단 문의를 공식 문의 폼으로 접수합니다. 담당자가 확인한 뒤 이메일 또는 연락처로 안내합니다.',
    description: '기존 key 호환용 후원 카드 설명입니다.',
    groupName: 'home.support',
    inputType: 'textarea',
    key: 'home.support.cardDescription',
    label: '후원 카드 설명',
    sortOrder: 1190,
  },
] satisfies SiteTextDefinition[]

export const siteTextDefaults: Record<string, string> = Object.fromEntries(
  siteTextDefinitions.map((definition) => [
    definition.key,
    definition.defaultValue,
  ]),
)
