import type { SiteCopyDefinition } from '../types/siteEditor'

// Stable explicit keys; defaults retain the original JSX text, including whitespace.
export const aboutCopyDefinitions: SiteCopyDefinition[] = [
  {"key":"about.introduction.text1","page":"about","section":"소개 · 첫 화면","label":"청소년의 목소리로","defaultValue":"청소년의 목소리로","multiline":false},
  {"key":"about.introduction.text2","page":"about","section":"소개 · 첫 화면","label":"세상과 이웃을","defaultValue":"세상과 이웃을","multiline":false},
  {"key":"about.introduction.text3","page":"about","section":"소개 · 첫 화면","label":"이어","defaultValue":"이어","multiline":false},
  {"key":"about.introduction.text4","page":"about","section":"소개 · 첫 화면","label":"갑니다.","defaultValue":"갑니다.","multiline":false},
  {"key":"about.introduction.text5","page":"about","section":"소개 · 첫 화면","label":"2014년 서울모테트합창단이 음악재단을 설립하며 청소년아카데미 산하에 창단했습니다. 정기연주회, 뮤직캠프, ","defaultValue":"2014년 서울모테트합창단이 음악재단을 설립하며 청소년아카데미 산하에 창단했습니다. 정기연주회, 뮤직캠프, 초청·봉사연주, 해외 비전투어를 통해 음악적 역량과 공동체성, 세계시민의식을 함께 기릅니다.","multiline":true},
  {"key":"about.introduction.alt6","page":"about","section":"소개 · 첫 화면","label":"사진 설명 · 2018년 유럽 비전투어에 참여한 서울모테트청소년합창단 단체 사진","defaultValue":"2018년 유럽 비전투어에 참여한 서울모테트청소년합창단 단체 사진","multiline":false},
  {"key":"about.introduction.text7","page":"about","section":"소개 · 첫 화면","label":"서로 다른 목소리가","defaultValue":"서로 다른 목소리가","multiline":false},
  {"key":"about.introduction.text8","page":"about","section":"소개 · 첫 화면","label":"하나의 공동체가 됩니다.","defaultValue":"하나의 공동체가 됩니다.","multiline":false},
  {"key":"about.introduction.text9","page":"about","section":"소개 · 첫 화면","label":"생명의 노래  ·  섬김의 노래  ·  희망의 노래","defaultValue":"생명의 노래  ·  섬김의 노래  ·  희망의 노래","multiline":false},
  {"key":"about.foundingStory.text1","page":"about","section":"소개 · 창단 배경","label":"합창음악의 위대한 힘으로,","defaultValue":"합창음악의 위대한 힘으로,","multiline":false},
  {"key":"about.foundingStory.text2","page":"about","section":"소개 · 창단 배경","label":"사람과 사회를 세웁니다.","defaultValue":"사람과 사회를 세웁니다.","multiline":false},
  {"key":"about.foundingStory.alt3","page":"about","section":"소개 · 창단 배경","label":"사진 설명 · 서울모테트청소년합창단 제1회 정기연주회 무대","defaultValue":"서울모테트청소년합창단 제1회 정기연주회 무대","multiline":false},
  {"key":"about.foundingStory.text4","page":"about","section":"소개 · 창단 배경","label":"제1회 정기연주회","defaultValue":"제1회 정기연주회","multiline":false},
  {"key":"about.foundingStory.text5","page":"about","section":"소개 · 창단 배경","label":"함께 세운 첫 무대","defaultValue":"함께 세운 첫 무대","multiline":false},
  {"key":"about.foundingStory.text6","page":"about","section":"소개 · 창단 배경","label":"교회음악의 바른 이상을","defaultValue":"교회음악의 바른 이상을","multiline":false},
  {"key":"about.foundingStory.text7","page":"about","section":"소개 · 창단 배경","label":"다음 세대에게.","defaultValue":"다음 세대에게.","multiline":false},
  {"key":"about.foundingStory.text8","page":"about","section":"소개 · 창단 배경","label":"서울모테트음악재단 설립 25주년과 재단 설립을 기념하여 창단되었습니다. 청소년들이 정통 합창음악을 통해 음악","defaultValue":"서울모테트음악재단 설립 25주년과 재단 설립을 기념하여 창단되었습니다. 청소년들이 정통 합창음악을 통해 음악적 역량과 인성을 키우며, 이웃과 사회에 나눔과 사랑을 실천하는 인재로 성장하도록 돕는 것이 출발점이었습니다.","multiline":true},
  {"key":"about.foundingStory.text9","page":"about","section":"소개 · 창단 배경","label":"음악의 참된 의미와 가치를 배우며,","defaultValue":"음악의 참된 의미와 가치를 배우며,","multiline":false},
  {"key":"about.foundingStory.text10","page":"about","section":"소개 · 창단 배경","label":"이웃을 향한 나눔과 사랑을 실천합니다.","defaultValue":"이웃을 향한 나눔과 사랑을 실천합니다.","multiline":false},
  {"key":"about.spirit.ariaLabel1","page":"about","section":"소개 · 합창단 정신","label":"접근성 이름 · 음악의 참된 의미와 가치를 배웁니다.","defaultValue":"음악의 참된 의미와 가치를 배웁니다.","multiline":false},
  {"key":"about.spirit.text2","page":"about","section":"소개 · 합창단 정신","label":"음악의 참된 의미와","defaultValue":"음악의 참된 의미와","multiline":false},
  {"key":"about.spirit.text3","page":"about","section":"소개 · 합창단 정신","label":"가치를","defaultValue":"가치를 ","multiline":false},
  {"key":"about.spirit.text4","page":"about","section":"소개 · 합창단 정신","label":"배웁니다.","defaultValue":"배웁니다.","multiline":false},
  {"key":"about.spirit.text5","page":"about","section":"소개 · 합창단 정신","label":"합창음악을 통해 지성·인성·영성의 조화를 이루고, 스스로를 공동체와 사회의 구성원으로 인식하도록 돕습니다. ","defaultValue":"합창음악을 통해 지성·인성·영성의 조화를 이루고, 스스로를 공동체와 사회의 구성원으로 인식하도록 돕습니다. 음악은 개인의 기량을 넘어 이웃을 향한 위로와 희망, 나눔과 사랑으로 이어집니다.","multiline":true},
  {"key":"about.spirit.text6","page":"about","section":"소개 · 합창단 정신","label":"삶에 지친 영혼을 치유하는 생명의 노래,","defaultValue":"삶에 지친 영혼을 치유하는 생명의 노래,","multiline":false},
  {"key":"about.spirit.text7","page":"about","section":"소개 · 합창단 정신","label":"세상과 이웃을 향한 섬김과 희망의 노래.","defaultValue":"세상과 이웃을 향한 섬김과 희망의 노래.","multiline":false},
  {"key":"about.spirit.ariaLabel8","page":"about","section":"소개 · 합창단 정신","label":"접근성 이름 · 합창단이 중요하게 여기는 네 가지 가치","defaultValue":"합창단이 중요하게 여기는 네 가지 가치","multiline":false},
  {"key":"about.spirit.text9","page":"about","section":"소개 · 합창단 정신","label":"“나의 노래를 가르쳐 부르게 하라”  ·  신 31:19","defaultValue":"“나의 노래를 가르쳐 부르게 하라”  ·  신 31:19","multiline":false},
  {"key":"about.spirit.text10","page":"about","section":"소개 · 합창단 정신","label":"한 사람의 성장을 넘어, 함께 살아가는 태도를 배웁니다.","defaultValue":"한 사람의 성장을 넘어, 함께 살아가는 태도를 배웁니다.","multiline":false},
  {"key":"about.education.text1","page":"about","section":"소개 · 교육","label":"잘 부르는 기술보다","defaultValue":"잘 부르는 기술보다","multiline":false},
  {"key":"about.education.text2","page":"about","section":"소개 · 교육","label":"함께 듣는 태도를.","defaultValue":"함께 듣는 태도를.","multiline":false},
  {"key":"about.education.alt3","page":"about","section":"소개 · 교육","label":"사진 설명 · 지휘자와 단원들이 함께 악보를 살피는 서울모테트청소년합창단 리허설","defaultValue":"지휘자와 단원들이 함께 악보를 살피는 서울모테트청소년합창단 리허설","multiline":false},
  {"key":"about.education.text4","page":"about","section":"소개 · 교육","label":"서로를 듣는 순간부터","defaultValue":"서로를 듣는 순간부터","multiline":false},
  {"key":"about.education.text5","page":"about","section":"소개 · 교육","label":"앙상블은 시작됩니다.","defaultValue":"앙상블은 시작됩니다.","multiline":false},
  {"key":"about.education.text6","page":"about","section":"소개 · 교육","label":"합창은 발성, 악보 읽기, 협업 태도를","defaultValue":"합창은 발성, 악보 읽기, 협업 태도를","multiline":false},
  {"key":"about.education.text7","page":"about","section":"소개 · 교육","label":"함께 배우는 교육입니다.","defaultValue":"함께 배우는 교육입니다.","multiline":false},
  {"key":"about.education.text8","page":"about","section":"소개 · 교육","label":"정기연주회로 예술적 성장을, 수련·뮤직캠프로 공동체성과 리더십을, 해외 비전투어로 문화 다양성에 대한 존중과","defaultValue":"정기연주회로 예술적 성장을, 수련·뮤직캠프로 공동체성과 리더십을, 해외 비전투어로 문화 다양성에 대한 존중과 세계시민의식을 배웁니다.","multiline":false},
  {"key":"about.education.text9","page":"about","section":"소개 · 교육","label":"무대와 삶으로 이어지는 다섯 가지 교육","defaultValue":"무대와 삶으로 이어지는 다섯 가지 교육","multiline":false},
  {"key":"conductor.conductorProfileDocument.text1","page":"conductor","section":"지휘자 · 표제와 안내","label":"지휘자 소개","defaultValue":"지휘자 소개","multiline":false},
  {"key":"conductor.conductorProfileDocument.ariaLabel2","page":"conductor","section":"지휘자 · 표제와 안내","label":"접근성 이름 · 현재 주요 역할","defaultValue":"현재 주요 역할","multiline":false},
  {"key":"accompanist.accompanistProfiles.text1","page":"accompanist","section":"반주자 · 표제와 안내","label":"반주자 소개","defaultValue":"반주자 소개","multiline":false},
  {"key":"accompanist.accompanistProfiles.text2","page":"accompanist","section":"반주자 · 표제와 안내","label":"연습과 무대에서 합창단과 함께하는 두 반주자의 학력과 현재 활동을 소개합니다.","defaultValue":"연습과 무대에서 합창단과 함께하는 두 반주자의 학력과 현재 활동을 소개합니다.","multiline":false},
  {"key":"accompanist.accompanistProfiles.title3","page":"accompanist","section":"반주자 · 표제와 안내","label":"등록된 반주자 소개가 없습니다","defaultValue":"등록된 반주자 소개가 없습니다","multiline":false},
  {"key":"members.membersArchiveExperience.text1","page":"members","section":"단원 · 명단과 필터","label":"함께한 모든 이름이","defaultValue":"함께한 모든 이름이","multiline":false},
  {"key":"members.membersArchiveExperience.text2","page":"members","section":"단원 · 명단과 필터","label":"지금의 합창단을 만듭니다.","defaultValue":"지금의 합창단을 만듭니다.","multiline":false},
  {"key":"members.membersArchiveExperience.text3","page":"members","section":"단원 · 명단과 필터","label":"2014년 창단 이후 서울모테트청소년합창단과 함께한 단원을 한 자리에서 소개합니다.","defaultValue":"2014년 창단 이후 서울모테트청소년합창단과 함께한 단원을 한 자리에서 소개합니다.","multiline":false},
  {"key":"members.membersArchiveExperience.text4","page":"members","section":"단원 · 명단과 필터","label":"현재 활동 중인 단원도 이 아카이브에 함께 기록됩니다.","defaultValue":"현재 활동 중인 단원도 이 아카이브에 함께 기록됩니다.","multiline":false},
  {"key":"members.membersArchiveExperience.text5","page":"members","section":"단원 · 명단과 필터","label":"이름은 공개 설정에 따라 전체·부분·비공개 방식으로 표시됩니다.","defaultValue":"이름은 공개 설정에 따라 전체·부분·비공개 방식으로 표시됩니다.","multiline":false},
  {"key":"members.membersArchiveExperience.text6","page":"members","section":"단원 · 명단과 필터","label":"단원 아카이브","defaultValue":"단원 아카이브","multiline":false},
  {"key":"members.membersArchiveExperience.text7","page":"members","section":"단원 · 명단과 필터","label":"현재 활동 중인 단원과 이전 활동 단원을 한 명단 안에서 살펴봅니다.","defaultValue":"현재 활동 중인 단원과 이전 활동 단원을 한 명단 안에서 살펴봅니다.","multiline":false},
  {"key":"members.membersArchiveExperience.text8","page":"members","section":"단원 · 명단과 필터","label":"현재 활동 단원 포함","defaultValue":"현재 활동 단원 포함","multiline":false},
  {"key":"members.membersArchiveExperience.ariaLabel9","page":"members","section":"단원 · 명단과 필터","label":"접근성 이름 · 활동 상태 필터","defaultValue":"활동 상태 필터","multiline":false},
  {"key":"members.membersArchiveExperience.ariaLabel10","page":"members","section":"단원 · 명단과 필터","label":"접근성 이름 · 파트 필터","defaultValue":"파트 필터","multiline":false},
  {"key":"members.membersArchiveExperience.text11","page":"members","section":"단원 · 명단과 필터","label":"조건에 맞는 공개 단원","defaultValue":"조건에 맞는 공개 단원 ","multiline":false},
  {"key":"members.membersArchiveExperience.text12","page":"members","section":"단원 · 명단과 필터","label":"조건에 맞는 공개 단원이 없습니다.","defaultValue":"조건에 맞는 공개 단원이 없습니다.","multiline":false},
  {"key":"members.membersArchiveExperience.text13","page":"members","section":"단원 · 명단과 필터","label":"활동 상태나 파트 필터를 바꾸어 다시 살펴보세요.","defaultValue":"활동 상태나 파트 필터를 바꾸어 다시 살펴보세요.","multiline":false},
  {"key":"members.membersArchiveExperience.text14","page":"members","section":"단원 · 명단과 필터","label":"모든 활동 시기와 파트가 한 아카이브 안에서 이어집니다.","defaultValue":"모든 활동 시기와 파트가 한 아카이브 안에서 이어집니다.","multiline":false},
  {"key":"members.membersArchiveExperience.text15","page":"members","section":"단원 · 명단과 필터","label":"가나다순 · PART INDEX","defaultValue":"가나다순 · PART INDEX","multiline":false},
  {"key":"history.historyCueSheetExperience.title1","page":"history","section":"연혁 · 안내와 기록 보기","label":"등록된 연혁이 없습니다","defaultValue":"등록된 연혁이 없습니다","multiline":false},
  {"key":"history.historyCueSheetExperience.text2","page":"history","section":"연혁 · 안내와 기록 보기","label":"함께한 무대의 기록","defaultValue":"함께한 무대의 기록","multiline":false},
  {"key":"history.historyCueSheetExperience.text3","page":"history","section":"연혁 · 안내와 기록 보기","label":"연도를 고르고, 필요한 장면을 펼쳐보세요.","defaultValue":"연도를 고르고, 필요한 장면을 펼쳐보세요.","multiline":false},
  {"key":"history.historyCueSheetExperience.text4","page":"history","section":"연혁 · 안내와 기록 보기","label":"한 줄의 기록이","defaultValue":"한 줄의 기록이","multiline":false},
  {"key":"history.historyCueSheetExperience.text5","page":"history","section":"연혁 · 안내와 기록 보기","label":"한 장면으로 펼쳐집니다.","defaultValue":"한 장면으로 펼쳐집니다.","multiline":false},
  {"key":"history.historyCueSheetExperience.text6","page":"history","section":"연혁 · 안내와 기록 보기","label":"창단 이후의 무대와 배움, 그리고 함께한 목소리를 공연 기록지처럼 차례로 펼쳐봅니다.","defaultValue":"창단 이후의 무대와 배움, 그리고 함께한 목소리를 공연 기록지처럼 차례로 펼쳐봅니다.","multiline":false},
  {"key":"history.historyCueSheetExperience.ariaLabel7","page":"history","section":"연혁 · 안내와 기록 보기","label":"접근성 이름 · 연도별 연혁 바로가기","defaultValue":"연도별 연혁 바로가기","multiline":false},
  {"key":"history.historyCueSheetExperience.ariaLabel8","page":"history","section":"연혁 · 안내와 기록 보기","label":"접근성 이름 · 합창단 연혁","defaultValue":"합창단 연혁","multiline":false},
  {"key":"history.historyCueSheetExperience.text9","page":"history","section":"연혁 · 안내와 기록 보기","label":"기록은 끝나지 않고, 다음 목소리로 이어집니다.","defaultValue":"기록은 끝나지 않고, 다음 목소리로 이어집니다.","multiline":false},
  {"key":"spirit.spiritHero.alt1","page":"spirit","section":"정신 · 첫 화면","label":"사진 설명 · 지휘자와 함께 연습하는 서울모테트청소년합창단","defaultValue":"지휘자와 함께 연습하는 서울모테트청소년합창단","multiline":false},
  {"key":"spirit.spiritHero.text2","page":"spirit","section":"정신 · 첫 화면","label":"정신은 선언이 아니라","defaultValue":"정신은 선언이 아니라","multiline":false},
  {"key":"spirit.spiritHero.text3","page":"spirit","section":"정신 · 첫 화면","label":"이어 온","defaultValue":"이어 온","multiline":false},
  {"key":"spirit.spiritHero.text4","page":"spirit","section":"정신 · 첫 화면","label":"선택","defaultValue":"선택","multiline":false},
  {"key":"spirit.spiritHero.text5","page":"spirit","section":"정신 · 첫 화면","label":"입니다.","defaultValue":"입니다.","multiline":false},
  {"key":"spirit.spiritHero.text6","page":"spirit","section":"정신 · 첫 화면","label":"마음을 담은","defaultValue":"마음을 담은","multiline":false},
  {"key":"spirit.spiritHero.text7","page":"spirit","section":"정신 · 첫 화면","label":"음악으로","defaultValue":"음악으로","multiline":false},
  {"key":"spirit.spiritHero.text8","page":"spirit","section":"정신 · 첫 화면","label":"다음","defaultValue":"다음 ","multiline":false},
  {"key":"spirit.spiritHero.text9","page":"spirit","section":"정신 · 첫 화면","label":"세대","defaultValue":"세대","multiline":false},
  {"key":"spirit.spiritHero.text10","page":"spirit","section":"정신 · 첫 화면","label":"를","defaultValue":"를","multiline":false},
  {"key":"spirit.spiritHero.text11","page":"spirit","section":"정신 · 첫 화면","label":"세웁니다.","defaultValue":"세웁니다.","multiline":false},
  {"key":"spirit.spiritHero.text12","page":"spirit","section":"정신 · 첫 화면","label":"정직한 음악에서 시작해","defaultValue":"정직한 음악에서 시작해","multiline":false},
  {"key":"spirit.spiritHero.text13","page":"spirit","section":"정신 · 첫 화면","label":"다음 세대의 성장으로 이어집니다.","defaultValue":"다음 세대의 성장으로 이어집니다.","multiline":false},
  {"key":"spirit.heritageTimeline.text1","page":"spirit","section":"정신 · 계승","label":"시간은 흘렀지만","defaultValue":"시간은 흘렀지만","multiline":false},
  {"key":"spirit.heritageTimeline.text2","page":"spirit","section":"정신 · 계승","label":"정신은","defaultValue":"정신은","multiline":false},
  {"key":"spirit.heritageTimeline.text3","page":"spirit","section":"정신 · 계승","label":"이어졌습니다.","defaultValue":"이어졌습니다.","multiline":false},
  {"key":"spirit.heritageTimeline.text4","page":"spirit","section":"정신 · 계승","label":"한 세대의 음악적 헌신이 재단과 청소년 교육으로 이어지고, 오늘의 공동체가 되었습니다.","defaultValue":"한 세대의 음악적 헌신이 재단과 청소년 교육으로 이어지고, 오늘의 공동체가 되었습니다.","multiline":false},
  {"key":"spirit.heritageTimeline.alt5","page":"spirit","section":"정신 · 계승","label":"사진 설명 · 서울모테트청소년합창단 연습 장면","defaultValue":"서울모테트청소년합창단 연습 장면","multiline":false},
  {"key":"spirit.heritageTimeline.text6","page":"spirit","section":"정신 · 계승","label":"연습에서 삶으로 이어지는 합창교육","defaultValue":"연습에서 삶으로 이어지는 합창교육","multiline":false},
  {"key":"spirit.motetMeaning.text1","page":"spirit","section":"정신 · 모테트의 의미","label":"모테트는","defaultValue":"모테트는","multiline":false},
  {"key":"spirit.motetMeaning.text2","page":"spirit","section":"정신 · 모테트의 의미","label":"여러","defaultValue":"여러 ","multiline":false},
  {"key":"spirit.motetMeaning.text3","page":"spirit","section":"정신 · 모테트의 의미","label":"목소리","defaultValue":"목소리","multiline":false},
  {"key":"spirit.motetMeaning.text4","page":"spirit","section":"정신 · 모테트의 의미","label":"로,","defaultValue":"로,","multiline":false},
  {"key":"spirit.motetMeaning.text5","page":"spirit","section":"정신 · 모테트의 의미","label":"하나의 원칙을","defaultValue":"하나의 원칙을","multiline":false},
  {"key":"spirit.motetMeaning.text6","page":"spirit","section":"정신 · 모테트의 의미","label":"만듭니다.","defaultValue":"만듭니다.","multiline":false},
  {"key":"spirit.spiritManifesto.text1","page":"spirit","section":"정신 · 선언문","label":"합창은 더 크게 부르는 법보다,","defaultValue":"합창은 더 크게 부르는 법보다,","multiline":false},
  {"key":"spirit.spiritManifesto.text2","page":"spirit","section":"정신 · 선언문","label":"함께 듣는","defaultValue":"함께 듣는 ","multiline":false},
  {"key":"spirit.spiritManifesto.text3","page":"spirit","section":"정신 · 선언문","label":"태도","defaultValue":"태도","multiline":false},
  {"key":"spirit.spiritManifesto.text4","page":"spirit","section":"정신 · 선언문","label":"를","defaultValue":"를","multiline":false},
  {"key":"spirit.spiritManifesto.text5","page":"spirit","section":"정신 · 선언문","label":"배우는 일입니다.","defaultValue":"배우는 일입니다.","multiline":false},
  {"key":"spirit.faithSection.text1","page":"spirit","section":"정신 · 정직한 음악","label":"정직한","defaultValue":"정직한","multiline":false},
  {"key":"spirit.faithSection.text2","page":"spirit","section":"정신 · 정직한 음악","label":"음악은","defaultValue":" 음악은","multiline":false},
  {"key":"spirit.faithSection.text3","page":"spirit","section":"정신 · 정직한 음악","label":"다음 세대의","defaultValue":"다음 세대의","multiline":false},
  {"key":"spirit.faithSection.text4","page":"spirit","section":"정신 · 정직한 음악","label":"기준","defaultValue":"기준","multiline":false},
  {"key":"spirit.faithSection.text5","page":"spirit","section":"정신 · 정직한 음악","label":"이 됩니다.","defaultValue":"이 됩니다.","multiline":false},
  {"key":"spirit.valuesSection.text1","page":"spirit","section":"정신 · 네 가지 태도","label":"우리가","defaultValue":"우리가 ","multiline":false},
  {"key":"spirit.valuesSection.text2","page":"spirit","section":"정신 · 네 가지 태도","label":"한 음","defaultValue":"한 음","multiline":false},
  {"key":"spirit.valuesSection.text3","page":"spirit","section":"정신 · 네 가지 태도","label":"을","defaultValue":"을","multiline":false},
  {"key":"spirit.valuesSection.text4","page":"spirit","section":"정신 · 네 가지 태도","label":"대하는 네 가지","defaultValue":"대하는 네 가지","multiline":false},
  {"key":"spirit.valuesSection.text5","page":"spirit","section":"정신 · 네 가지 태도","label":"태도","defaultValue":"태도","multiline":false},
  {"key":"spirit.valuesSection.text6","page":"spirit","section":"정신 · 네 가지 태도","label":"네 가지 원칙은 연습과 공연, 공동체 안에서 함께 작동하는 하나의 기준입니다.","defaultValue":"네 가지 원칙은 연습과 공연, 공동체 안에서 함께 작동하는 하나의 기준입니다.","multiline":false},
  {"key":"spirit.valuesSection.ariaLabel7","page":"spirit","section":"정신 · 네 가지 태도","label":"접근성 이름 · 합창단 핵심 가치","defaultValue":"합창단 핵심 가치","multiline":false},
  {"key":"spirit.communitySection.text1","page":"spirit","section":"정신 · 공동체","label":"서로","defaultValue":"서로 ","multiline":false},
  {"key":"spirit.communitySection.text2","page":"spirit","section":"정신 · 공동체","label":"다른","defaultValue":"다른","multiline":false},
  {"key":"spirit.communitySection.text3","page":"spirit","section":"정신 · 공동체","label":"목소리가","defaultValue":" 목소리가","multiline":false},
  {"key":"spirit.communitySection.text4","page":"spirit","section":"정신 · 공동체","label":"하나의","defaultValue":"하나의","multiline":false},
  {"key":"spirit.communitySection.text5","page":"spirit","section":"정신 · 공동체","label":"공동체가 됩니다.","defaultValue":"공동체가 됩니다.","multiline":false},
  {"key":"spirit.communitySection.alt6","page":"spirit","section":"정신 · 공동체","label":"사진 설명 · 함께 악보를 들고 연습하는 서울모테트청소년합창단","defaultValue":"함께 악보를 들고 연습하는 서울모테트청소년합창단","multiline":false},
  {"key":"spirit.educationSection.text1","page":"spirit","section":"정신 · 교육","label":"음악을 배우는","defaultValue":"음악을 배우는","multiline":false},
  {"key":"spirit.educationSection.text2","page":"spirit","section":"정신 · 교육","label":"다섯 가지","defaultValue":"다섯 가지","multiline":false},
  {"key":"spirit.educationSection.text3","page":"spirit","section":"정신 · 교육","label":"성장","defaultValue":"성장","multiline":false},
  {"key":"spirit.educationSection.text4","page":"spirit","section":"정신 · 교육","label":"의 장면","defaultValue":"의 장면","multiline":false},
  {"key":"spirit.educationSection.text5","page":"spirit","section":"정신 · 교육","label":"좋은 합창은 무대에서 갑자기 완성되지 않습니다. 듣고, 이해하고, 조율하고, 약속을 지키는 일상의 반복이 사","defaultValue":"좋은 합창은 무대에서 갑자기 완성되지 않습니다. 듣고, 이해하고, 조율하고, 약속을 지키는 일상의 반복이 사람을 세웁니다.","multiline":false},
  {"key":"spirit.educationSection.ariaLabel6","page":"spirit","section":"정신 · 교육","label":"접근성 이름 · 성장의 다섯 단계","defaultValue":"성장의 다섯 단계","multiline":false},
  {"key":"spirit.closingCta.text1","page":"spirit","section":"정신 · 참여 안내","label":"함께 부르는","defaultValue":"함께 부르는","multiline":false},
  {"key":"spirit.closingCta.text2","page":"spirit","section":"정신 · 참여 안내","label":"다음 세대의","defaultValue":"다음 세대의","multiline":false},
  {"key":"spirit.closingCta.text3","page":"spirit","section":"정신 · 참여 안내","label":"울림에","defaultValue":"울림에","multiline":false},
  {"key":"spirit.closingCta.text4","page":"spirit","section":"정신 · 참여 안내","label":"동참하세요.","defaultValue":"동참하세요.","multiline":false},
  {"key":"about.values.01.title","page":"about","section":"소개 · 네 가지 가치","label":"음악적 역량과 예술성 · 제목","defaultValue":"음악적 역량과 예술성","multiline":false},
  {"key":"about.values.01.body","page":"about","section":"소개 · 네 가지 가치","label":"음악적 역량과 예술성 · 설명","defaultValue":"음악 작품과 가사를 이해하고, 듣기·발성·앙상블로 예술적 역량을 키웁니다.","multiline":false},
  {"key":"about.values.02.title","page":"about","section":"소개 · 네 가지 가치","label":"교회음악의 바른 이상 · 제목","defaultValue":"교회음악의 바른 이상","multiline":false},
  {"key":"about.values.02.body","page":"about","section":"소개 · 네 가지 가치","label":"교회음악의 바른 이상 · 설명","defaultValue":"기독교 정신과 교회음악의 전통 위에서 지성·인성·영성의 조화를 추구합니다.","multiline":false},
  {"key":"about.values.03.title","page":"about","section":"소개 · 네 가지 가치","label":"함께 부르는 공동체 · 제목","defaultValue":"함께 부르는 공동체","multiline":false},
  {"key":"about.values.03.body","page":"about","section":"소개 · 네 가지 가치","label":"함께 부르는 공동체 · 설명","defaultValue":"공동체 훈련으로 사회성과 자신감, 리더십을 기르고 서로를 존중합니다.","multiline":false},
  {"key":"about.values.04.title","page":"about","section":"소개 · 네 가지 가치","label":"다음 세대 교육 · 제목","defaultValue":"다음 세대 교육","multiline":false},
  {"key":"about.values.04.body","page":"about","section":"소개 · 네 가지 가치","label":"다음 세대 교육 · 설명","defaultValue":"정기연주회, 캠프, 봉사, 해외 비전투어로 예술적 성장과 세계시민의식을 키웁니다.","multiline":false},
  {"key":"about.learning.01.title","page":"about","section":"소개 · 배움의 과정","label":"호흡 · 제목","defaultValue":"호흡","multiline":false},
  {"key":"about.learning.01.body","page":"about","section":"소개 · 배움의 과정","label":"호흡 · 설명","defaultValue":"발성과 악보 읽기로 자신의 소리와 기초를 익힙니다.","multiline":false},
  {"key":"about.learning.02.title","page":"about","section":"소개 · 배움의 과정","label":"듣기 · 제목","defaultValue":"듣기","multiline":false},
  {"key":"about.learning.02.body","page":"about","section":"소개 · 배움의 과정","label":"듣기 · 설명","defaultValue":"상대 파트와 작품을 들으며 해석과 균형을 배웁니다.","multiline":false},
  {"key":"about.learning.03.title","page":"about","section":"소개 · 배움의 과정","label":"앙상블 · 제목","defaultValue":"앙상블","multiline":false},
  {"key":"about.learning.03.body","page":"about","section":"소개 · 배움의 과정","label":"앙상블 · 설명","defaultValue":"공동체 훈련으로 사회성·자신감·리더십을 기릅니다.","multiline":false},
  {"key":"about.learning.04.title","page":"about","section":"소개 · 배움의 과정","label":"나눔 · 제목","defaultValue":"나눔","multiline":false},
  {"key":"about.learning.04.body","page":"about","section":"소개 · 배움의 과정","label":"나눔 · 설명","defaultValue":"초청·봉사연주로 위로와 희망을 전하고 이웃을 섬깁니다.","multiline":false},
  {"key":"about.programs.01.title","page":"about","section":"소개 · 교육 활동","label":"정기연주회 · 제목","defaultValue":"정기연주회","multiline":false},
  {"key":"about.programs.01.body","page":"about","section":"소개 · 교육 활동","label":"정기연주회 · 설명","defaultValue":"음악적 역량과 예술적 성장","multiline":false},
  {"key":"about.programs.02.title","page":"about","section":"소개 · 교육 활동","label":"수련·뮤직캠프 · 제목","defaultValue":"수련·뮤직캠프","multiline":false},
  {"key":"about.programs.02.body","page":"about","section":"소개 · 교육 활동","label":"수련·뮤직캠프 · 설명","defaultValue":"정체성·사회성·자신감·리더십","multiline":false},
  {"key":"about.programs.03.title","page":"about","section":"소개 · 교육 활동","label":"초청·봉사연주 · 제목","defaultValue":"초청·봉사연주","multiline":false},
  {"key":"about.programs.03.body","page":"about","section":"소개 · 교육 활동","label":"초청·봉사연주 · 설명","defaultValue":"위로와 희망을 전하고 이웃을 섬김","multiline":false},
  {"key":"about.programs.04.title","page":"about","section":"소개 · 교육 활동","label":"해외 비전투어 · 제목","defaultValue":"해외 비전투어","multiline":false},
  {"key":"about.programs.04.body","page":"about","section":"소개 · 교육 활동","label":"해외 비전투어 · 설명","defaultValue":"문화적 다양성과 세계시민의식","multiline":false},
  {"key":"about.programs.05.title","page":"about","section":"소개 · 교육 활동","label":"특별활동 · 제목","defaultValue":"특별활동","multiline":false},
  {"key":"about.programs.05.body","page":"about","section":"소개 · 교육 활동","label":"특별활동 · 설명","defaultValue":"방송·드라마 촬영·음원 녹음","multiline":false},
  {"key":"members.status.all","page":"members","section":"단원 · 필터와 상태","label":"전체 단원","defaultValue":"전체 단원","multiline":false},
  {"key":"members.status.active","page":"members","section":"단원 · 필터와 상태","label":"현재 활동","defaultValue":"현재 활동","multiline":false},
  {"key":"members.status.alumni","page":"members","section":"단원 · 필터와 상태","label":"이전 활동","defaultValue":"이전 활동","multiline":false},
  {"key":"members.part.all","page":"members","section":"단원 · 필터와 상태","label":"전체 파트","defaultValue":"전체 파트","multiline":false},
  {"key":"members.part.soprano","page":"members","section":"단원 · 필터와 상태","label":"소프라노","defaultValue":"소프라노","multiline":false},
  {"key":"members.part.alto","page":"members","section":"단원 · 필터와 상태","label":"알토","defaultValue":"알토","multiline":false},
  {"key":"members.part.tenor","page":"members","section":"단원 · 필터와 상태","label":"테너","defaultValue":"테너","multiline":false},
  {"key":"members.part.bass","page":"members","section":"단원 · 필터와 상태","label":"베이스","defaultValue":"베이스","multiline":false},
  {"key":"members.part.staff","page":"members","section":"단원 · 필터와 상태","label":"스태프","defaultValue":"스태프","multiline":false},
  {"key":"members.badge.active","page":"members","section":"단원 · 필터와 상태","label":"현재 활동","defaultValue":"현재 활동","multiline":false},
  {"key":"members.badge.alumni","page":"members","section":"단원 · 필터와 상태","label":"함께한 단원","defaultValue":"함께한 단원","multiline":false},
  {"key":"history.photo.caption","page":"history","section":"연혁 · 안내와 기록 보기","label":"첫 번째 공개 사진 기록","defaultValue":"첫 번째 공개 사진 기록","multiline":false},
  {"key":"history.action.collapse","page":"history","section":"연혁 · 안내와 기록 보기","label":"모두 접기","defaultValue":"모두 접기","multiline":false},
  {"key":"history.action.expand","page":"history","section":"연혁 · 안내와 기록 보기","label":"모두 펼치기","defaultValue":"모두 펼치기","multiline":false},
  {"key":"history.detail.empty","page":"history","section":"연혁 · 안내와 기록 보기","label":"상세 기록은 준비 중입니다.","defaultValue":"상세 기록은 준비 중입니다.","multiline":false},
  {"key":"history.photo.alt","page":"history","section":"연혁 · 안내와 기록 보기","label":"서울모테트청소년합창단 연혁 이미지","defaultValue":"서울모테트청소년합창단 연혁 이미지","multiline":false},
  {"key":"accompanist.photoLabel","page":"accompanist","section":"반주자 · 접근성 안내","label":"반주자 프로필 사진","defaultValue":"반주자 프로필 사진","multiline":false},
  {"key":"accompanist.educationLabel","page":"accompanist","section":"반주자 · 접근성 안내","label":"학력과 주요 이력","defaultValue":"학력과 주요 이력","multiline":false},
  {"key":"accompanist.currentLabel","page":"accompanist","section":"반주자 · 접근성 안내","label":"현재 활동","defaultValue":"현재 활동","multiline":false},
  {"key":"spirit.lineage.0.title","page":"spirit","section":"정신 · 계승","label":"1989 · 제목","defaultValue":"서울모테트합창단의 시작","multiline":false},
  {"key":"spirit.lineage.0.body","page":"spirit","section":"정신 · 계승","label":"1989 · 설명","defaultValue":"순수 합창음악과 교회음악의 바른 방향을 세우고자 한 전문 음악가들의 자발적 헌신에서 서울모테트합창단의 여정이 시작되었습니다.","multiline":false},
  {"key":"spirit.lineage.1.title","page":"spirit","section":"정신 · 계승","label":"2014 · 제목","defaultValue":"서울모테트음악재단과 청소년합창단","multiline":false},
  {"key":"spirit.lineage.1.body","page":"spirit","section":"정신 · 계승","label":"2014 · 설명","defaultValue":"서울모테트합창단 창단 25주년을 계기로 음악과 신앙, 마음의 성장을 함께 품은 다음세대 합창교육의 사명이 제도적으로 확장되었습니다.","multiline":false},
  {"key":"spirit.lineage.2.title","page":"spirit","section":"정신 · 계승","label":"현재 · 제목","defaultValue":"청소년 합창교육 공동체","multiline":false},
  {"key":"spirit.lineage.2.body","page":"spirit","section":"정신 · 계승","label":"현재 · 설명","defaultValue":"청소년들은 정통 레퍼토리와 교회음악, 봉사 연주와 국제교류를 통해 합창 기본기와 무대 경험을 함께 배웁니다.","multiline":false},
  {"key":"spirit.lineage.3.title","page":"spirit","section":"정신 · 계승","label":"미래 · 제목","defaultValue":"다음 세대의 울림","multiline":false},
  {"key":"spirit.lineage.3.body","page":"spirit","section":"정신 · 계승","label":"미래 · 설명","defaultValue":"합창은 청소년이 자신의 목소리를 발견하고, 이웃의 소리를 들으며, 세계를 향한 나눔과 평화의 꿈을 품게 하는 교육의 길이 됩니다.","multiline":false},
  {"key":"spirit.manifesto.label0","page":"spirit","section":"정신 · 선언문","label":"합창 기본기","defaultValue":"합창 기본기","multiline":false},
  {"key":"spirit.manifesto.label1","page":"spirit","section":"정신 · 선언문","label":"함께 듣는 연습","defaultValue":"함께 듣는 연습","multiline":false},
  {"key":"spirit.manifesto.label2","page":"spirit","section":"정신 · 선언문","label":"공연 활동","defaultValue":"공연 활동","multiline":false},
  {"key":"spirit.manifesto.label3","page":"spirit","section":"정신 · 선언문","label":"이어지는 정신","defaultValue":"이어지는 정신","multiline":false},
  {"key":"spirit.faith.lead","page":"spirit","section":"정신 · 정직한 음악","label":"신앙과 기억 소개","defaultValue":"서울모테트청소년합창단은 “후대에 노래를 가르치라”는 부르심 앞에서 시작된 다음세대 합창교육 공동체입니다.","multiline":false},
  {"key":"spirit.faith.paragraph0","page":"spirit","section":"정신 · 정직한 음악","label":"신앙과 기억 문단 1","defaultValue":"노래는 단순한 예술 활동이 아닙니다. 공동체가 믿고 고백해 온 신앙과 역사, 정체성을 다음 세대의 마음에 새기는 교육의 언어입니다.","multiline":false},
  {"key":"spirit.faith.paragraph1","page":"spirit","section":"정신 · 정직한 음악","label":"신앙과 기억 문단 2","defaultValue":"청소년기의 민감하고 형성적인 시간에 말씀의 노래를 배우고 함께 부른다는 것은, 신앙을 지식이 아닌 체험으로, 교리를 살아 있는 고백으로 내면화하는 과정입니다.","multiline":true},
  {"key":"spirit.faith.paragraph2","page":"spirit","section":"정신 · 정직한 음악","label":"신앙과 기억 문단 3","defaultValue":"서울모테트청소년합창단은 합창을 통해 음악적 재능만이 아니라, 신앙의 기억과 공동체를 향한 마음, 삶의 방향을 다음 세대 안에 심는 일을 사명으로 삼습니다.","multiline":true},
  {"key":"spirit.scripture.0.label","page":"spirit","section":"정신 · 성경 말씀","label":"신명기 31:19 · 출처","defaultValue":"신명기 31:19","multiline":false},
  {"key":"spirit.scripture.0.text","page":"spirit","section":"정신 · 성경 말씀","label":"신명기 31:19 · 본문","defaultValue":"이 노래를 써서 이스라엘 자손들에게 가르쳐 그들의 입으로 부르게 하라","multiline":false},
  {"key":"spirit.scripture.0.note","page":"spirit","section":"정신 · 성경 말씀","label":"신명기 31:19 · 설명","defaultValue":"노래를 통해 신앙과 기억을 다음 세대에 새기라는 명령","multiline":false},
  {"key":"spirit.scripture.1.label","page":"spirit","section":"정신 · 성경 말씀","label":"사사기 2:10 · 출처","defaultValue":"사사기 2:10","multiline":false},
  {"key":"spirit.scripture.1.text","page":"spirit","section":"정신 · 성경 말씀","label":"사사기 2:10 · 본문","defaultValue":"그 후에 일어난 다른 세대는 여호와를 알지 못하였다","multiline":false},
  {"key":"spirit.scripture.1.note","page":"spirit","section":"정신 · 성경 말씀","label":"사사기 2:10 · 설명","defaultValue":"신앙과 기억의 계승이 멈출 때 다음 세대가 잃어버릴 수 있는 것에 대한 경고","multiline":false},
  {"key":"spirit.community.lead","page":"spirit","section":"정신 · 공동체","label":"공동체 소개","defaultValue":"합창은 나의 소리를 크게 내는 훈련이 아니라, 타인의 소리를 듣고 나의 자리를 조율하는 공동체의 예술입니다.","multiline":false},
  {"key":"spirit.community.centerLabel","page":"spirit","section":"정신 · 공동체","label":"사진 설명","defaultValue":"하나의 울림","multiline":false},
  {"key":"spirit.community.closing","page":"spirit","section":"정신 · 공동체","label":"마무리 문구","defaultValue":"혼자 부르면 소리입니다. 함께 들으면 화음이 됩니다.\n서로를 들을 때, 공동체가 됩니다.","multiline":true},
  {"key":"spirit.voices.0.part","page":"spirit","section":"정신 · 목소리와 역할","label":"소프라노 · 이름","defaultValue":"소프라노","multiline":false},
  {"key":"spirit.voices.0.meaning","page":"spirit","section":"정신 · 목소리와 역할","label":"소프라노 · 역할","defaultValue":"밝은 선율, 시작하는 용기","multiline":false},
  {"key":"spirit.voices.1.part","page":"spirit","section":"정신 · 목소리와 역할","label":"알토 · 이름","defaultValue":"알토","multiline":false},
  {"key":"spirit.voices.1.meaning","page":"spirit","section":"정신 · 목소리와 역할","label":"알토 · 역할","defaultValue":"깊은 균형, 보이지 않는 지지","multiline":false},
  {"key":"spirit.voices.2.part","page":"spirit","section":"정신 · 목소리와 역할","label":"테너 · 이름","defaultValue":"테너","multiline":false},
  {"key":"spirit.voices.2.meaning","page":"spirit","section":"정신 · 목소리와 역할","label":"테너 · 역할","defaultValue":"연결과 확장","multiline":false},
  {"key":"spirit.voices.3.part","page":"spirit","section":"정신 · 목소리와 역할","label":"베이스 · 이름","defaultValue":"베이스","multiline":false},
  {"key":"spirit.voices.3.meaning","page":"spirit","section":"정신 · 목소리와 역할","label":"베이스 · 역할","defaultValue":"기초와 따뜻한 지지","multiline":false},
  {"key":"spirit.voices.4.part","page":"spirit","section":"정신 · 목소리와 역할","label":"스태프 · 이름","defaultValue":"스태프","multiline":false},
  {"key":"spirit.voices.4.meaning","page":"spirit","section":"정신 · 목소리와 역할","label":"스태프 · 역할","defaultValue":"섬김과 질서","multiline":false},
  {"key":"spirit.learning.0.step","page":"spirit","section":"정신 · 성장의 다섯 단계","label":"듣기 · 탭 이름","defaultValue":"듣기","multiline":false},
  {"key":"spirit.learning.0.title","page":"spirit","section":"정신 · 성장의 다섯 단계","label":"듣기 · 제목","defaultValue":"먼저 듣는 사람으로 자랍니다","multiline":false},
  {"key":"spirit.learning.0.body","page":"spirit","section":"정신 · 성장의 다섯 단계","label":"듣기 · 설명","defaultValue":"합창은 자신의 소리를 내기 전에 다른 사람의 호흡과 음색을 듣는 법을 가르칩니다.","multiline":false},
  {"key":"spirit.learning.1.step","page":"spirit","section":"정신 · 성장의 다섯 단계","label":"해석하기 · 탭 이름","defaultValue":"해석하기","multiline":false},
  {"key":"spirit.learning.1.title","page":"spirit","section":"정신 · 성장의 다섯 단계","label":"해석하기 · 제목","defaultValue":"음악 안의 뜻을 배웁니다","multiline":false},
  {"key":"spirit.learning.1.body","page":"spirit","section":"정신 · 성장의 다섯 단계","label":"해석하기 · 설명","defaultValue":"단원들은 가사와 작품의 역사, 신학적 의미와 음악적 구조를 함께 배우며 노래의 깊이를 이해합니다.","multiline":false},
  {"key":"spirit.learning.2.step","page":"spirit","section":"정신 · 성장의 다섯 단계","label":"조율하기 · 탭 이름","defaultValue":"조율하기","multiline":false},
  {"key":"spirit.learning.2.title","page":"spirit","section":"정신 · 성장의 다섯 단계","label":"조율하기 · 제목","defaultValue":"나의 소리를 공동체 안에 맞춥니다","multiline":false},
  {"key":"spirit.learning.2.body","page":"spirit","section":"정신 · 성장의 다섯 단계","label":"조율하기 · 설명","defaultValue":"내 목소리의 크기와 색깔을 조절하며, 전체 하모니를 위해 자신의 소리를 조율하는 법을 배웁니다.","multiline":false},
  {"key":"spirit.learning.3.step","page":"spirit","section":"정신 · 성장의 다섯 단계","label":"약속 지키기 · 탭 이름","defaultValue":"약속 지키기","multiline":false},
  {"key":"spirit.learning.3.title","page":"spirit","section":"정신 · 성장의 다섯 단계","label":"약속 지키기 · 제목","defaultValue":"한 음과 한 약속을 소중히 여깁니다","multiline":false},
  {"key":"spirit.learning.3.body","page":"spirit","section":"정신 · 성장의 다섯 단계","label":"약속 지키기 · 설명","defaultValue":"악보를 꾸준히 준비하고, 연습 시간의 약속과 파트 안의 자리를 소중히 여기며 서로를 신뢰하는 태도를 기릅니다.","multiline":false},
  {"key":"spirit.learning.4.step","page":"spirit","section":"정신 · 성장의 다섯 단계","label":"섬기기 · 탭 이름","defaultValue":"섬기기","multiline":false},
  {"key":"spirit.learning.4.title","page":"spirit","section":"정신 · 성장의 다섯 단계","label":"섬기기 · 제목","defaultValue":"무대 밖에서도 음악과 꿈을 나눕니다","multiline":false},
  {"key":"spirit.learning.4.body","page":"spirit","section":"정신 · 성장의 다섯 단계","label":"섬기기 · 설명","defaultValue":"봉사 연주와 국제교류의 자리에서 음악이 이웃을 위로하고 공동체를 세우며, 평화와 화해의 메시지를 전하는 언어가 될 수 있음을 경험합니다.","multiline":false},
  {"key":"spirit.motet.quoteFallback","page":"spirit","section":"정신 · 기본 안내","label":"하나가 되기 위해 같아지는 것이 아니라, 다름을 들으며 정확히 맞춰 갑니다.","defaultValue":"하나가 되기 위해 같아지는 것이 아니라, 다름을 들으며 정확히 맞춰 갑니다.","multiline":false},
  {"key":"spirit.action.joinFallback","page":"spirit","section":"정신 · 기본 안내","label":"입단 안내","defaultValue":"입단 안내","multiline":false},
  {"key":"spirit.action.supportFallback","page":"spirit","section":"정신 · 기본 안내","label":"후원 참여","defaultValue":"후원 참여","multiline":false},
  { key: 'conductor.activity.alt', page: 'conductor', section: '지휘자 · 사진 설명', label: '공연 사진 기본 설명', defaultValue: '서울모테트청소년합창단 공연 사진' },
  { key: 'conductor.performance.alt', page: 'conductor', section: '지휘자 · 사진 설명', label: '기본 공연 사진 설명', defaultValue: '서울모테트청소년합창단과 오케스트라가 함께하는 공연 사진' },
  { key: 'conductor.profile.altSuffix', page: 'conductor', section: '지휘자 · 사진 설명', label: '이름·역할 뒤 프로필 안내', defaultValue: '공식 프로필' },
  { key: 'history.hero.alt', page: 'history', section: '연혁 · 사진 설명', label: '기본 첫 화면 사진 설명', defaultValue: '서울모테트청소년합창단 2025 제11회 정기연주회 무대 사진' },
  { key: 'members.group.elementary', page: 'members', section: '단원 · 그룹 안내', label: '초등부', defaultValue: '초등부' },
  { key: 'members.group.middle', page: 'members', section: '단원 · 그룹 안내', label: '중등부', defaultValue: '중등부' },
  { key: 'members.group.high', page: 'members', section: '단원 · 그룹 안내', label: '고등부', defaultValue: '고등부' },
  { key: 'members.group.university', page: 'members', section: '단원 · 그룹 안내', label: '대학부', defaultValue: '대학부' },
  { key: 'members.group.alumni', page: 'members', section: '단원 · 그룹 안내', label: '역대단원', defaultValue: '역대단원' },
  { key: 'members.part.other', page: 'members', section: '단원 · 파트 안내', label: '기타 파트 이름', defaultValue: '합창단' },
  {"key":"about.introduction.english1","page":"about","section":"소개 · 영문 라벨","label":"접근성·보조 라벨 · MAKING VOICES MATTER","defaultValue":"MAKING VOICES MATTER","multiline":false},
  {"key":"about.introduction.english2","page":"about","section":"소개 · 영문 라벨","label":"ABOUT SMYC","defaultValue":"ABOUT SMYC","multiline":false},
  {"key":"about.introduction.english3","page":"about","section":"소개 · 영문 라벨","label":"VOICES","defaultValue":"VOICES","multiline":false},
  {"key":"about.introduction.english4","page":"about","section":"소개 · 영문 라벨","label":"EUROPE TOUR","defaultValue":"EUROPE TOUR","multiline":false},
  {"key":"about.foundingStory.english1","page":"about","section":"소개 · 영문 라벨","label":"WHY WE BEGAN","defaultValue":"WHY WE BEGAN","multiline":false},
  {"key":"about.foundingStory.english2","page":"about","section":"소개 · 영문 라벨","label":"ARCHIVE / FIRST CONCERT","defaultValue":"ARCHIVE / FIRST CONCERT","multiline":false},
  {"key":"about.spirit.english1","page":"about","section":"소개 · 영문 라벨","label":"OUR SPIRIT","defaultValue":"OUR SPIRIT","multiline":false},
  {"key":"about.spirit.english2","page":"about","section":"소개 · 영문 라벨","label":"ONE VOICE","defaultValue":"ONE VOICE","multiline":false},
  {"key":"about.spirit.english3","page":"about","section":"소개 · 영문 라벨","label":"LISTEN  ·  RESPECT  ·  HARMONIZE  ·  SHARE","defaultValue":"LISTEN  ·  RESPECT  ·  HARMONIZE  ·  SHARE","multiline":false},
  {"key":"about.spirit.english4","page":"about","section":"소개 · 영문 라벨","label":"MUSIC BECOMES CHARACTER.","defaultValue":"MUSIC BECOMES CHARACTER.","multiline":false},
  {"key":"about.education.english1","page":"about","section":"소개 · 영문 라벨","label":"HOW WE LEARN","defaultValue":"HOW WE LEARN","multiline":false},
  {"key":"about.education.english2","page":"about","section":"소개 · 영문 라벨","label":"Learning","defaultValue":"Learning","multiline":false},
  {"key":"about.education.english3","page":"about","section":"소개 · 영문 라벨","label":"by Listening","defaultValue":"by Listening","multiline":false},
  {"key":"about.education.english4","page":"about","section":"소개 · 영문 라벨","label":"PRACTICE / LISTENING FIRST","defaultValue":"PRACTICE / LISTENING FIRST","multiline":false},
  {"key":"about.education.english5","page":"about","section":"소개 · 영문 라벨","label":"BREATHE  ·  LISTEN  ·  HARMONIZE  ·  SHARE","defaultValue":"BREATHE  ·  LISTEN  ·  HARMONIZE  ·  SHARE","multiline":false},
  {"key":"about.education.english6","page":"about","section":"소개 · 영문 라벨","label":"PROGRAMS IN PRACTICE","defaultValue":"PROGRAMS IN PRACTICE","multiline":false},
  {"key":"conductor.conductorProfileDocument.english1","page":"conductor","section":"지휘자 · 영문 라벨","label":"CONDUCTOR","defaultValue":"CONDUCTOR","multiline":false},
  {"key":"conductor.conductorProfileDocument.english2","page":"conductor","section":"지휘자 · 영문 라벨","label":"CONDUCTOR","defaultValue":"CONDUCTOR","multiline":false},
  {"key":"conductor.conductorProfileDocument.english3","page":"conductor","section":"지휘자 · 영문 라벨","label":"CURRENT","defaultValue":"CURRENT","multiline":false},
  {"key":"conductor.conductorProfileDocument.english4","page":"conductor","section":"지휘자 · 영문 라벨","label":"SMYC CONDUCTOR PROFILE","defaultValue":"SMYC CONDUCTOR PROFILE","multiline":false},
  {"key":"accompanist.accompanistProfiles.english1","page":"accompanist","section":"반주자 · 영문 라벨","label":"ACCOMPANIST PROFILE","defaultValue":"ACCOMPANIST PROFILE ","multiline":false},
  {"key":"accompanist.accompanistProfiles.english2","page":"accompanist","section":"반주자 · 영문 라벨","label":"Accompanists.","defaultValue":"Accompanists.","multiline":false},
  {"key":"accompanist.accompanistProfiles.english3","page":"accompanist","section":"반주자 · 영문 라벨","label":"ACCOMPANIST","defaultValue":"ACCOMPANIST","multiline":false},
  {"key":"accompanist.accompanistProfiles.english4","page":"accompanist","section":"반주자 · 영문 라벨","label":"Piano Accompanist","defaultValue":"Piano Accompanist","multiline":false},
  {"key":"accompanist.accompanistProfiles.english5","page":"accompanist","section":"반주자 · 영문 라벨","label":"CURRENT","defaultValue":"CURRENT","multiline":false},
  {"key":"accompanist.accompanistProfiles.english6","page":"accompanist","section":"반주자 · 영문 라벨","label":"ACCOMPANIST PROFILE","defaultValue":"ACCOMPANIST PROFILE","multiline":false},
  {"key":"members.membersArchiveExperience.english1","page":"members","section":"단원 · 영문 라벨","label":"MEMBER ARCHIVE / SEOUL","defaultValue":"MEMBER ARCHIVE / SEOUL","multiline":false},
  {"key":"members.membersArchiveExperience.english2","page":"members","section":"단원 · 영문 라벨","label":"접근성·보조 라벨 · All voices. One archive.","defaultValue":"All voices. One archive.","multiline":false},
  {"key":"members.membersArchiveExperience.english3","page":"members","section":"단원 · 영문 라벨","label":"All voices.","defaultValue":"All voices.","multiline":false},
  {"key":"members.membersArchiveExperience.english4","page":"members","section":"단원 · 영문 라벨","label":"One archive.","defaultValue":"One archive.","multiline":false},
  {"key":"members.membersArchiveExperience.english5","page":"members","section":"단원 · 영문 라벨","label":"ALL MEMBERS ·","defaultValue":"ALL MEMBERS ·","multiline":false},
  {"key":"members.membersArchiveExperience.english6","page":"members","section":"단원 · 영문 라벨","label":"ACTIVE & FORMER · BY PART","defaultValue":"ACTIVE & FORMER · BY PART","multiline":false},
  {"key":"members.membersArchiveExperience.english7","page":"members","section":"단원 · 영문 라벨","label":"ALL MEMBERS / ONE ARCHIVE","defaultValue":"ALL MEMBERS / ONE ARCHIVE","multiline":false},
  {"key":"history.historyCueSheetExperience.english1","page":"history","section":"연혁 · 영문 라벨","label":"HISTORY / CUE SHEET","defaultValue":"HISTORY / CUE SHEET","multiline":false},
  {"key":"history.historyCueSheetExperience.english2","page":"history","section":"연혁 · 영문 라벨","label":"HISTORY / CUE SHEET","defaultValue":"HISTORY / CUE SHEET","multiline":false},
  {"key":"history.historyCueSheetExperience.english3","page":"history","section":"연혁 · 영문 라벨","label":"PERFORMANCE INDEX","defaultValue":"PERFORMANCE INDEX","multiline":false},
  {"key":"history.historyCueSheetExperience.english4","page":"history","section":"연혁 · 영문 라벨","label":"YEAR / INDEX","defaultValue":"YEAR / INDEX","multiline":false},
  {"key":"history.historyCueSheetExperience.english5","page":"history","section":"연혁 · 영문 라벨","label":"PERFORMANCE RECORD","defaultValue":"PERFORMANCE RECORD","multiline":false},
  {"key":"history.historyCueSheetExperience.english6","page":"history","section":"연혁 · 영문 라벨","label":"STAGE NOTE","defaultValue":"STAGE NOTE","multiline":false},
  {"key":"history.historyCueSheetExperience.english7","page":"history","section":"연혁 · 영문 라벨","label":"LIVING ARCHIVE /","defaultValue":"LIVING ARCHIVE / ","multiline":false},
  {"key":"spirit.spiritHero.english1","page":"spirit","section":"정신 · 영문 라벨","label":"SPIRIT","defaultValue":"SPIRIT","multiline":false},
  {"key":"spirit.spiritHero.english2","page":"spirit","section":"정신 · 영문 라벨","label":"SPIRIT","defaultValue":"SPIRIT","multiline":false},
  {"key":"spirit.heritageTimeline.english1","page":"spirit","section":"정신 · 영문 라벨","label":"OUR LINEAGE","defaultValue":"OUR LINEAGE","multiline":false},
  {"key":"spirit.motetMeaning.english1","page":"spirit","section":"정신 · 영문 라벨","label":"MOTET","defaultValue":"MOTET","multiline":false},
  {"key":"spirit.motetMeaning.english2","page":"spirit","section":"정신 · 영문 라벨","label":"THE NAME · THE ROOT · THE STANDARD","defaultValue":"THE NAME · THE ROOT · THE STANDARD","multiline":false},
  {"key":"spirit.motetMeaning.english3","page":"spirit","section":"정신 · 영문 라벨","label":"M","defaultValue":"M","multiline":false},
  {"key":"spirit.motetMeaning.english4","page":"spirit","section":"정신 · 영문 라벨","label":"many voices — one intention","defaultValue":"many voices — one intention","multiline":false},
  {"key":"spirit.faithSection.english1","page":"spirit","section":"정신 · 영문 라벨","label":"HONEST","defaultValue":"HONEST","multiline":false},
  {"key":"spirit.communitySection.english1","page":"spirit","section":"정신 · 영문 라벨","label":"LISTEN","defaultValue":"LISTEN","multiline":false},
  {"key":"spirit.educationSection.english1","page":"spirit","section":"정신 · 영문 라벨","label":"HOW WE GROW","defaultValue":"HOW WE GROW","multiline":false},
  {"key":"spirit.closingCta.english1","page":"spirit","section":"정신 · 영문 라벨","label":"ONE","defaultValue":"ONE","multiline":false},
  {"key":"spirit.closingCta.english2","page":"spirit","section":"정신 · 영문 라벨","label":"VOICE","defaultValue":"VOICE","multiline":false},
  { key: 'about.facts.0.caption', page: 'about', section: '소개 · 영문 설명', label: '창단 연도 설명', defaultValue: 'FOUNDED IN SEOUL' },
  { key: 'about.facts.1.label', page: 'about', section: '소개 · 영문 설명', label: '청소년 표제', defaultValue: 'YOUTH' },
  { key: 'about.facts.1.caption', page: 'about', section: '소개 · 영문 설명', label: '합창단·아카데미 설명', defaultValue: 'CHOIR & ACADEMY' },
  { key: 'about.facts.2.label', page: 'about', section: '소개 · 영문 설명', label: '모테트 표제', defaultValue: 'MOTET' },
  { key: 'about.facts.2.caption', page: 'about', section: '소개 · 영문 설명', label: '배움의 가치 설명', defaultValue: 'LISTEN · LEARN · SING' },
  { key: 'about.values.01.english', page: 'about', section: '소개 · 네 가지 가치', label: '음악적 역량 영문 표제', defaultValue: 'MUSICAL ARTISTRY' },
  { key: 'about.values.02.english', page: 'about', section: '소개 · 네 가지 가치', label: '교회음악 영문 표제', defaultValue: 'SACRED IDEAL' },
  { key: 'about.values.03.english', page: 'about', section: '소개 · 네 가지 가치', label: '공동체 영문 표제', defaultValue: 'ONE COMMUNITY' },
  { key: 'about.values.04.english', page: 'about', section: '소개 · 네 가지 가치', label: '다음 세대 영문 표제', defaultValue: 'NEXT GENERATION' },
  { key: 'about.learning.01.english', page: 'about', section: '소개 · 배움의 과정', label: '호흡 영문 표제', defaultValue: 'BREATHE' },
  { key: 'about.learning.02.english', page: 'about', section: '소개 · 배움의 과정', label: '듣기 영문 표제', defaultValue: 'LISTEN' },
  { key: 'about.learning.03.english', page: 'about', section: '소개 · 배움의 과정', label: '앙상블 영문 표제', defaultValue: 'HARMONIZE' },
  { key: 'about.learning.04.english', page: 'about', section: '소개 · 배움의 과정', label: '나눔 영문 표제', defaultValue: 'SHARE' },
  { key: 'members.groupHeading.soprano', page: 'members', section: '단원 · 영문 그룹 이름', label: '소프라노 그룹 표제', defaultValue: 'SOPRANO' },
  { key: 'members.groupHeading.alto', page: 'members', section: '단원 · 영문 그룹 이름', label: '알토 그룹 표제', defaultValue: 'ALTO' },
  { key: 'members.groupHeading.tenor', page: 'members', section: '단원 · 영문 그룹 이름', label: '테너 그룹 표제', defaultValue: 'TENOR' },
  { key: 'members.groupHeading.bass-staff', page: 'members', section: '단원 · 영문 그룹 이름', label: '베이스·스태프 그룹 표제', defaultValue: 'BASS · STAFF' },
  { key: 'members.group.staffDisplay', page: 'members', section: '단원 · 영문 그룹 이름', label: '스태프 역할 표시', defaultValue: 'STAFF' },
  { key: 'spirit.lineage.now', page: 'spirit', section: '정신 · 계승', label: '현재 표제', defaultValue: 'NOW' },
  { key: 'spirit.lineage.next', page: 'spirit', section: '정신 · 계승', label: '미래 표제', defaultValue: 'NEXT' },
  { key: 'spirit.action.eyebrowFallback', page: 'spirit', section: '정신 · 참여 안내', label: '참여 안내 기본 영문 표제', defaultValue: 'JOIN THE HARMONY' },
]
