import { spawnSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'

// Explicit regression inventory. Archived visual-prototype contracts are not
// included through a broad glob; their status is tracked separately.
const tests = [
  'src/hooks/useAdminAuth.test.mjs',
  'src/hooks/useCrudList.test.mjs',
  'src/hooks/useUnsavedChangesGuard.test.mjs',
  'src/components/admin/AdminSingleRecordSection.test.mjs',
  'src/components/admin/AdminRecordForm.test.mjs',
  'src/components/admin/AdminRecordForm.safety.test.mjs',
  'src/components/admin/AdminRouteLoading.test.mjs',
  'src/components/admin/ImageUploader.test.mjs',
  'src/lib/storage.test.mjs',
  'src/lib/publicData.test.mjs',
  'src/lib/cmsDeletionSafety.test.mjs',
  'src/lib/sponsorPublicApi.test.mjs',
  'src/lib/intakeModel.test.mjs',
  'src/lib/intakeApi.test.mjs',
  'src/lib/publicIntakeIntegration.test.mjs',
  'scripts/check-supabase-live.test.mjs',
  'src/lib/aboutNavigation.test.mjs',
  'src/components/about/AboutOverviewExperience.contract.test.mjs',
  'src/components/about/ConductorProfileDocument.contract.test.mjs',
  'src/components/about/HistoryCueSheetExperience.contract.test.mjs',
  'src/components/about/historyCueSheetModel.test.mjs',
  'src/components/about/accompanistProfileModel.test.mjs',
  'src/components/about/careerRoleSelection.test.mjs',
  'src/components/concerts/concertScheduleModel.test.mjs',
  'src/utils/memberArchive.test.mjs',
  'src/components/about/MembersArchive.contract.test.mjs',
  'src/components/gallery/galleryViewModel.test.mjs',
  'src/components/join/joinApplicationModel.test.mjs',
  'src/lib/joinApplications.test.mjs',
  'src/lib/joinRecruitment.test.mjs',
  'src/pages/admin/AdminJoinPage.test.mjs',
  'src/pages/admin/AdminJoinApplicationsPage.test.mjs',
  'src/pages/admin/AdminSupportPledgesPage.test.mjs',
  'src/pages/admin/AdminDashboardPage.test.mjs',
  'scripts/public-copy-contract.test.mjs',
  'src/components/admin/adminModalFocus.test.mjs',
  'src/lib/cmsPagination.test.mjs',
  'src/lib/intakeLimits.test.mjs',
  'src/pages/admin/AdminSiteEditorPage.design.test.mjs',
  'src/pages/public/ContactPage.test.mjs',
  'src/pages/public/homeHoldScroll.test.mjs',
  'src/components/contact/contactFormModel.test.mjs',
  'src/components/contact/SupportPledgeForm.test.mjs',
  'src/lib/homeContent.contract.test.mjs',
  'src/lib/homeDeviceContent.test.mjs',
  'src/lib/homeResponsiveContent.test.mjs',
  'src/lib/homePreviewMode.test.mjs',
  'src/lib/homeTypography.test.mjs',
  'src/styles/homeTypography.contract.test.mjs',
  'src/components/admin/home/homeDeviceEditorModel.test.mjs',
  'src/components/home/HomeHeroSlideshow.image.test.mjs',
  'src/types/siteEditor.test.mjs',
  'src/lib/siteEditorModel.test.mjs',
  'src/lib/siteEditorApi.test.mjs',
  'src/lib/siteEditorPreview.test.mjs',
  'src/lib/siteEditorPublication.test.mjs',
  'src/lib/siteEditorSubmissionGuard.test.mjs',
  'src/content/siteCopyCatalog.test.mjs',
  'src/content/siteCopyAboutCatalog.test.mjs',
  'src/components/admin/site-editor/editorSessionModel.test.mjs',
  'src/components/admin/site-editor/EditorCopyPanel.test.mjs',
  'src/components/admin/site-editor/editorPreviewModel.test.mjs',
  'src/components/site-editor/SiteEditorProvider.test.mjs',
]

const result = spawnSync(process.execPath, ['--test', '--test-concurrency=4', ...tests], {
  cwd: fileURLToPath(new URL('..', import.meta.url)),
  stdio: 'inherit',
})
if (result.error) console.error(result.error.message)
process.exitCode = result.status ?? 1
