-- Restores active V2 home CMS copy to the approved pre-connection HTML reference.
-- Dynamic data in concerts, notices, gallery, join_info, sponsors and media tables is not changed.
WITH reference_copy(key, value) AS (
  VALUES
    ('home.about.ctaLabel', '합창단 소개 보기'),
    ('home.about.eyebrowEn', 'ABOUT'),
    ('home.about.eyebrowKo', '소개'),
    ('home.about.globalDescription', '서울에서 시작한 청소년 합창교육과 무대의 기록을 세계 관객과 공유합니다.'),
    ('home.about.globalTagline', 'Voice, learning and the stage'),
    ('home.about.paragraphs.1', '서울모테트청소년합창단은 청소년이 합창의 기본기, 악보 읽기, 무대 경험을 체계적으로 배우는 합창교육 공동체입니다.'),
    ('home.about.paragraphs.2', '정기 연습과 공연 활동을 통해 발성, 앙상블, 협업 태도를 함께 익힙니다.'),
    ('home.about.title', '서울모테트청소년합창단 소개'),
    ('home.archive.collapseLabel', '접기'),
    ('home.archive.ctaLabel', '갤러리 보기'),
    ('home.archive.description', '공연 사진, 연습 사진, 영상, 포스터를 모아 확인합니다.'),
    ('home.archive.emptyDescription', '현재 공개된 공연·연습 기록이 없습니다.'),
    ('home.archive.emptyTitle', '공개된 갤러리 자료가 없습니다'),
    ('home.archive.expandLabel', '기록 펼치기'),
    ('home.archive.eyebrowEn', 'ARCHIVE'),
    ('home.archive.eyebrowKo', '기록'),
    ('home.archive.title', '사진 · 영상 · 포스터'),
    ('home.choirProgram.eyebrowEn', 'CHOIR PROGRAM'),
    ('home.choirProgram.eyebrowKo', '교육'),
    ('home.choirProgram.items.education.description', '발성, 악보 읽기, 파트 연습, 앙상블 기본기를 체계적으로 배웁니다.'),
    ('home.choirProgram.items.education.displayOrder', '2'),
    ('home.choirProgram.items.education.isVisible', 'true'),
    ('home.choirProgram.items.education.title', '교육 목적'),
    ('home.choirProgram.items.foundation.description', '서울모테트합창단의 음악적 전통을 바탕으로 청소년 합창교육을 운영합니다.'),
    ('home.choirProgram.items.foundation.displayOrder', '1'),
    ('home.choirProgram.items.foundation.isVisible', 'true'),
    ('home.choirProgram.items.foundation.title', '창단 목적'),
    ('home.choirProgram.items.growth.description', '정기 연습과 공연 활동을 통해 협업 태도와 무대 경험을 쌓습니다.'),
    ('home.choirProgram.items.growth.displayOrder', '4'),
    ('home.choirProgram.items.growth.isVisible', 'true'),
    ('home.choirProgram.items.growth.title', '단원 성장'),
    ('home.choirProgram.items.performance.description', '정기연주회와 초청연주, 특별 무대를 준비하며 연습의 시간을 실제 무대 경험으로 연결합니다.'),
    ('home.choirProgram.items.performance.displayOrder', '3'),
    ('home.choirProgram.items.performance.isVisible', 'true'),
    ('home.choirProgram.items.performance.title', '연주 활동'),
    ('home.choirProgram.title', '교육과 활동'),
    ('home.concertProgram.concertsCtaLabel', '공연 일정 보기'),
    ('home.concertProgram.description', '다가오는 공연의 날짜, 장소, 공지사항을 확인합니다. 공연 정보가 확정되면 이 섹션에 반영됩니다.'),
    ('home.concertProgram.detailCtaLabel', '자세히 보기'),
    ('home.concertProgram.emptyConcertCtaLabel', '공연 일정 보기'),
    ('home.concertProgram.emptyConcertDescription', '새로운 공연 일정이 확정되면 이 공간에서 안내합니다.'),
    ('home.concertProgram.emptyConcertTitle', '등록된 공연이 없습니다'),
    ('home.concertProgram.emptyNoticeCtaLabel', '공지사항 보기'),
    ('home.concertProgram.emptyNoticeDescription', '새로운 공지와 합창단 소식을 준비하고 있습니다.'),
    ('home.concertProgram.emptyNoticeTitle', '등록된 공지사항이 없습니다'),
    ('home.concertProgram.eyebrowEn', 'CONCERTS & NEWS'),
    ('home.concertProgram.eyebrowKo', '공연'),
    ('home.concertProgram.inquiryCtaLabel', '문의'),
    ('home.concertProgram.noticePanelCtaLabel', '전체 보기'),
    ('home.concertProgram.noticePanelTitle', '프로그램 노트'),
    ('home.concertProgram.noticesCtaLabel', '공지사항 보기'),
    ('home.concertProgram.title', '공연과 소식'),
    ('home.heroSupplement.fallbackDescription', '서울모테트청소년합창단은 청소년이 합창을 배우고 정기 연습과 공연을 경험하는 음악교육 공동체입니다.'),
    ('home.heroSupplement.mottoChips.1', '진심을 담은 음악'),
    ('home.heroSupplement.mottoChips.2', '정기 연습'),
    ('home.heroSupplement.mottoChips.3', '공연 활동'),
    ('home.joinLetter.ctaLabel', '입단지원서 작성하기'),
    ('home.joinLetter.description', '모집 대상, 연습 일정, 오디션 절차를 확인한 뒤 입단지원서를 제출할 수 있습니다. 제출 후 담당자가 보호자 연락처로 안내합니다.'),
    ('home.joinLetter.eyebrowEn', 'JOIN'),
    ('home.joinLetter.eyebrowKo', '입단'),
    ('home.joinLetter.title', '노래를 향한 아이보다
함께 듣고 성장할 준비가 된 아이를 기다립니다'),
    ('home.quickActions.concert.ctaLabel', '공연 일정 보기'),
    ('home.quickActions.concert.description', '정기연주회, 초청연주, 공지사항을 확인합니다.'),
    ('home.quickActions.concert.displayOrder', '2'),
    ('home.quickActions.concert.isVisible', 'true'),
    ('home.quickActions.concert.title', '공연 일정'),
    ('home.quickActions.join.ctaLabel', '입단 안내 보기'),
    ('home.quickActions.join.description', '모집 대상, 연습 시간, 지원 절차를 확인하고 입단지원서로 이동합니다.'),
    ('home.quickActions.join.displayOrder', '1'),
    ('home.quickActions.join.isVisible', 'true'),
    ('home.quickActions.join.title', '입단 안내'),
    ('home.quickActions.support.ctaLabel', '후원·문의 보기'),
    ('home.quickActions.support.description', '후원 상담과 일반 문의를 공식 문의 폼으로 접수합니다.'),
    ('home.quickActions.support.displayOrder', '3'),
    ('home.quickActions.support.isVisible', 'true'),
    ('home.quickActions.support.title', '후원·문의'),
    ('home.scoreBook.cover.titleLines', '함께 부르는
우리의 노래'),
    ('home.scoreBook.eyebrowKo', '악보'),
    ('home.scoreBook.final.primaryCtaLabel', '우리의 활동 보기'),
    ('home.scoreBook.final.secondaryCtaLabel', '공연과 소식'),
    ('home.scoreBook.final.summary', '체계적인 앙상블 교육과 정기 연습·공연을 통해 음악으로 함께 성장합니다.'),
    ('home.scoreBook.final.titleLines', '서로 다른 목소리로,
같은 음악을 완성합니다'),
    ('home.scoreBook.leftPage.body', '합창단의 교육 방향과 활동 흐름을 한 화면에서 안내합니다.'),
    ('home.scoreBook.leftPage.calloutBody', '한 곡을 준비하며 단원들은 음정, 박자, 발음, 호흡을 반복해서 맞춥니다.'),
    ('home.scoreBook.leftPage.calloutTitle', '연습이 남기는 것'),
    ('home.scoreBook.leftPage.keywords', '발성 · 악보 · 파트'),
    ('home.scoreBook.leftPage.titleLines', '서로 다른 목소리로,
같은 음악을 완성합니다'),
    ('home.scoreBook.rightPage.body', '파트별 역할을 익히고, 다른 단원의 소리를 들으며 함께 맞춰 갑니다.'),
    ('home.scoreBook.rightPage.calloutBody', '연습한 곡은 정기연주회, 초청연주, 나눔 공연에서 발표됩니다.'),
    ('home.scoreBook.rightPage.calloutTitle', '무대가 이어 주는 것'),
    ('home.scoreBook.rightPage.keywords', '앙상블 · 공연 · 안내'),
    ('home.scoreBook.rightPage.prefix', '공동체 연습'),
    ('home.scoreBook.rightPage.titleLines', '파트별 역할과
앙상블을 배웁니다'),
    ('home.scoreBook.valueItems.ensemble.description', '내 파트를 준비하는 마음'),
    ('home.scoreBook.valueItems.ensemble.displayOrder', '4'),
    ('home.scoreBook.valueItems.ensemble.isVisible', 'true'),
    ('home.scoreBook.valueItems.ensemble.label', '약속'),
    ('home.scoreBook.valueItems.guide.description', '노래 너머의 삶을 바라보는 눈'),
    ('home.scoreBook.valueItems.guide.displayOrder', '6'),
    ('home.scoreBook.valueItems.guide.isVisible', 'true'),
    ('home.scoreBook.valueItems.guide.label', '비전'),
    ('home.scoreBook.valueItems.part.description', '약속한 시간을 지키는 힘'),
    ('home.scoreBook.valueItems.part.displayOrder', '3'),
    ('home.scoreBook.valueItems.part.isVisible', 'true'),
    ('home.scoreBook.valueItems.part.label', '꾸준함'),
    ('home.scoreBook.valueItems.score.description', '서로의 자리를 살피는 태도'),
    ('home.scoreBook.valueItems.score.displayOrder', '2'),
    ('home.scoreBook.valueItems.score.isVisible', 'true'),
    ('home.scoreBook.valueItems.score.label', '어울림'),
    ('home.scoreBook.valueItems.stage.description', '다른 소리와 함께 숨 쉬는 일'),
    ('home.scoreBook.valueItems.stage.displayOrder', '5'),
    ('home.scoreBook.valueItems.stage.isVisible', 'true'),
    ('home.scoreBook.valueItems.stage.label', '조화'),
    ('home.scoreBook.valueItems.voice.description', '먼저 듣는 마음'),
    ('home.scoreBook.valueItems.voice.displayOrder', '1'),
    ('home.scoreBook.valueItems.voice.isVisible', 'true'),
    ('home.scoreBook.valueItems.voice.label', '귀 기울임'),
    ('home.spiritWrapper.ctaLabel', '정신 자세히 보기'),
    ('home.spiritWrapper.eyebrowKo', 'FIVE MOVEMENTS · MOTET SPIRIT'),
    ('home.spiritWrapper.title', '서울모테트청소년합창단의 다섯 가지 정신'),
    ('home.sponsors.ctaLabel', '후원사 전체 보기'),
    ('home.sponsors.description', '청소년들이 안정적으로 배우고 무대에 설 수 있도록 곁에서 힘을 보태는 후원사와 협력기관입니다. 보이지 않는 응원이 연습과 공연, 다음 무대의 준비로 이어집니다.'),
    ('home.sponsors.eyebrow', 'WITH OUR SUPPORTERS'),
    ('home.sponsors.title', '함께 세우는 손길'),
    ('home.supportLetter.description', '후원은 단순한 재정 지원이 아니라 다음 세대가 음악 안에서 자신을 발견하고 함께 이어가는 법을 배우도록 돕는 동행입니다.'),
    ('home.supportLetter.eyebrowEn', 'SUPPORT'),
    ('home.supportLetter.eyebrowKo', '후원'),
    ('home.supportLetter.pledgeDescription', '공연 초청, 후원 상담, 입단 문의를 공식 문의 폼으로 접수합니다. 담당자가 확인한 뒤 이메일 또는 연락처로 안내합니다.'),
    ('home.supportLetter.pledgeEyebrow', 'PLEDGE LETTER'),
    ('home.supportLetter.pledgeTitle', '문의 접수 안내'),
    ('home.supportLetter.primaryCtaLabel', '후원 상담 신청'),
    ('home.supportLetter.secondaryCtaLabel', '문의'),
    ('home.supportLetter.title', '후원은 청소년 합창교육과 공연 활동을 지원합니다')
)
UPDATE public.site_texts AS site_text
SET
  value = reference_copy.value,
  default_value = reference_copy.value,
  updated_at = timezone('utc', now())
FROM reference_copy
WHERE site_text.is_active
  AND site_text.key = reference_copy.key
  AND (
    site_text.value IS DISTINCT FROM reference_copy.value
    OR site_text.default_value IS DISTINCT FROM reference_copy.value
  );
